// Code generated by wasm2go. DO NOT EDIT.

package functions140

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop18(m *instance.Module, v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float64frombits(uint64(v0)) * math.Float64frombits(uint64(v1))))))
}

//go:nosplit
func f64_canon(x float64) float64 {
	if x != x {
		return math.Float64frombits(0x7ff8000000000000)
	}
	return x
}
