// Code generated by wasm2go. DO NOT EDIT.

package functions5

import (
	"encoding/binary"
	"github.com/stricttools/wasm-to-go/testdata/packages/memgrow/internal/functions7"
	"github.com/stricttools/wasm-to-go/testdata/packages/memgrow/internal/functions8"
	"github.com/stricttools/wasm-to-go/testdata/packages/memgrow/internal/functions9"
	"github.com/stricttools/wasm-to-go/testdata/packages/memgrow/internal/instance"
)

func Xclosed(m *instance.Module, v0 int32) int32 {
	mem := m.Memory
	var v1 int32
	binary.LittleEndian.PutUint32((*[4]byte)(mem[uint64(uint32(i32(0))) : uint64(uint32(i32(0)))+4])[:], uint32(i32(1)))
	var t0 int32
	switch t2 := uint(v0); t2 {
	case 0:
		t0 = functions9.Fn3(m)
		mem = m.Memory
	case 1:
		t0 = functions8.Fn4()
	case 2:
		t0 = functions7.Fn5(m)
		mem = m.Memory
	default:
		t0 = m.T0[t2].(func() int32)()
		mem = m.Memory
	}
	v1 = t0
	binary.LittleEndian.PutUint32((*[4]byte)(mem[uint64(uint32(v1*int32(65536))) : uint64(uint32(v1*int32(65536)))+4])[:], uint32(i32(99)))
	t1 := int32(binary.LittleEndian.Uint32((*[4]byte)(mem[uint64(uint32(v1*int32(65536))) : uint64(uint32(v1*int32(65536)))+4])[:]))
	return t1
}

//go:nosplit
func i32(x int32) int32 { return x }
