// Code generated by wasm2go. DO NOT EDIT.

package functions33

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop36(m *instance.Module, v0, v1 int64) int64 {
	t0 := i64_trunc_f64_s(math.Float64frombits(uint64(v0)))
	return t0
}

//go:nosplit
func i64_trunc_f64_s(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	}
	return int64(x)
}
