// Code generated by wasm2go. DO NOT EDIT.

//go:build !(386 || amd64 || arm64 || loong64 || ppc64le || wasm)

package wasm2go

import "runtime"

// A Module must be created by New and never copied.
// Calls through its function tables are compiled into direct calls
// on the receiver, which must be the Module New filled the tables for,
// and code outside the translated module must not change the tables.
type Module struct {
	t0       []any
	elements [][]any
	_env     Xenv
}

func New(v0 Xenv) *Module {
	m := new(Module)
	m._env = v0
	m.t0 = make([]any, 32)
	m.elements = [][]any{{fn1}, {m.fn0}}
	table_init(m.t0, m.elements[0], i32(16), 0, len(m.elements[0]))
	m.elements[0] = nil
	table_init(m.t0, m.elements[1], i32(17), 0, len(m.elements[1]))
	m.elements[1] = nil
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xenv = interface {
	Xjstimes3(v0 int32) int32
}

func (m *Module) fn0(v0 int32) int32 {
	return m._env.Xjstimes3(v0)
}
func fn1(v0 int32) int32 {
	return v0 + v0
}
func (m *Module) Xtimes2(v0 int32) int32 {
	var t0 int32
	switch t1 := uint(i32(16)); t1 {
	case 16:
		t0 = fn1(v0)
	case 17:
		t0 = m.fn0(v0)
	default:
		t0 = m.t0[t1].(func(int32) int32)(v0)
	}
	return t0
}
func (m *Module) Xtimes3(v0 int32) int32 {
	var t0 int32
	switch t1 := uint(i32(17)); t1 {
	case 16:
		t0 = fn1(v0)
	case 17:
		t0 = m.fn0(v0)
	default:
		t0 = m.t0[t1].(func(int32) int32)(v0)
	}
	return t0
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func i32(x int32) int32 { return x }

func table_init[T1, T2, T3 int | int32 | int64](tab, elems []any, dest T1, src T2, n T3) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(tab[x:y], elems[z:w])
}
