// Code generated by wasm2go. DO NOT EDIT.

//go:build !(386 || amd64 || arm64 || loong64 || ppc64le || wasm)

package tlsf

import (
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	memory     []byte
	memBacking []byte
	maxMem     int64
	g0         int32
}

func New() *Module {
	m := new(Module)
	m.maxMem = 1024
	m.memBacking = make([]byte, 0x20000)
	m.memory = m.memBacking
	m.g0 = i32(65536)
	return m
}

// MemoryMax is the most bytes the module's memory can grow to
// through its own memory.grow: its declared maximum.
func (m *Module) MemoryMax() int64 { return 67108864 }

// UseMemory moves the module's memory to the start of buf's backing array,
// where it keeps its size and contents and grows in place, without
// copying or allocating, as far as buf's capacity allows (past it, it moves
// to a new array in the Go heap). buf's bytes past the memory's size must
// be zero, and nothing else may write to them. UseMemory returns false,
// and leaves the memory where it is, when buf's capacity is less than the
// memory's size (a nil buf included). Slices of the memory taken before
// the call are stale after it, as after the memory grows.
func (m *Module) UseMemory(buf []byte) bool {
	n := len(m.memory)
	if cap(buf) < n {
		return false
	}
	buf = buf[:cap(buf)]
	copy(buf, m.memory)
	m.memBacking = buf
	m.memory = buf[:n:n]
	return true
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory Module

func (m *wasmMemory) Slice() *[]byte { return &m.memory }

func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow(&m.memory, &m.memBacking, delta, max)
}
func (m *Module) Xfree(v0 int32) {
	mem := m.memory
	if v0 != 0 {
		if v0&int32(15) != 0 {
			goto l0
		}
		v0 = v0 - int32(4)
		t0 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
		if t0&int32(1) != 0 {
			goto l0
		}
		m.fn1(v0)
	}
	return
l0:
	panic("unreachable")
}
func (m *Module) fn1(v0 int32) {
	mem := m.memory
	var v1, v2, v3, v4, v5 int32
	t0 := m.g0
	v4 = t0 - int32(16)
	m.g0 = v4
	t1 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
	t2 := v0
	v2 = t1
	v3 = t2 + v2&int32(-16)
	t3 := int32(binary.LittleEndian.Uint32(mem[uint32(v3):]))
	if t3&int32(1) != 0 {
		m.fn2(v3)
		t4 := int32(binary.LittleEndian.Uint32(mem[uint32(v3):]))
		t5 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
		t6 := t4 & int32(-16)
		v2 = t5
		v1 = t6 + v2&int32(-16)
		t7 := v0
		v2 = v1 | v2&int32(15)
		binary.LittleEndian.PutUint32(mem[uint32(t7):], uint32(v2))
		v3 = v0 + v1
	}
	{
		if v2&int32(2) == 0 {
			v1 = v0
			goto l0
		}
		t8 := int32(binary.LittleEndian.Uint32(mem[uint32(v0-int32(4)):]))
		v1 = v0 - t8
		m.fn2(v1)
		t9 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
		t10 := int32(binary.LittleEndian.Uint32(mem[uint32(v1):]))
		t11 := v1
		t12 := t9 & int32(-16)
		v0 = t10
		v2 = t12 + v0&int32(-16) | v0&int32(15)
		binary.LittleEndian.PutUint32(mem[uint32(t11):], uint32(v2))
	}
l0:
	binary.LittleEndian.PutUint32(mem[uint32(v1):], uint32(v2|int32(1)))
	v0 = v2 & int32(-16)
	binary.LittleEndian.PutUint32(mem[uint32(v0+v1-int32(4)):], uint32(v0))
	t13 := int32(binary.LittleEndian.Uint32(mem[uint32(v3):]))
	binary.LittleEndian.PutUint32(mem[uint32(v3):], uint32(t13|int32(2)))
	t14 := int32(binary.LittleEndian.Uint32(mem[uint32(v1):]))
	m.fn6(t14&int32(-16), int32(1), v4+int32(12), v4+int32(8))
	t15 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v4))+12:]))
	v2 = t15
	t16 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v4))+8:]))
	t17 := v2 << 6
	v3 = t16
	v5 = t17 + v3<<2 + int32(65640)
	t18 := int32(binary.LittleEndian.Uint32(mem[uint32(v5):]))
	v0 = t18
	binary.LittleEndian.PutUint32(mem[uint64(uint32(v1))+8:], uint32(i32(0)))
	binary.LittleEndian.PutUint32(mem[uint64(uint32(v1))+4:], uint32(v0))
	binary.LittleEndian.PutUint32(mem[uint32(v5):], uint32(v1))
	if v0 != 0 {
		binary.LittleEndian.PutUint32(mem[uint64(uint32(v0))+8:], uint32(v1))
	}
	t19 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(65536)):]))
	binary.LittleEndian.PutUint32(mem[uint32(i32(65536)):], uint32(t19|i32_shl(int32(1), v2)))
	v0 = v2<<2 + int32(65540)
	t20 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
	binary.LittleEndian.PutUint32(mem[uint32(v0):], uint32(t20|i32_shl(int32(1), v3)))
	m.g0 = v4 + int32(16)
}
func (m *Module) fn2(v0 int32) {
	mem := m.memory
	var v1, v2, v3 int32
	t0 := m.g0
	v2 = t0 - int32(16)
	m.g0 = v2
	t1 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
	m.fn6(t1&int32(-16), int32(1), v2+int32(12), v2+int32(8))
	t2 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v0))+8:]))
	v1 = t2
	t3 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v0))+4:]))
	v0 = t3
	if v0 != 0 {
		binary.LittleEndian.PutUint32(mem[uint64(uint32(v0))+8:], uint32(v1))
	}
	{
		if v1 != 0 {
			binary.LittleEndian.PutUint32(mem[uint64(uint32(v1))+4:], uint32(v0))
			goto l0
		}
		t4 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v2))+12:]))
		v3 = t4
		t5 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v2))+8:]))
		t6 := v3 << 6
		v1 = t5
		binary.LittleEndian.PutUint32(mem[uint32(t6+v1<<2+int32(65640)):], uint32(v0))
		if v0 != 0 {
			goto l0
		}
		v0 = v3<<2 + int32(65540)
		t7 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
		v1 = t7 & i32_rotl(int32(-2), v1)
		binary.LittleEndian.PutUint32(mem[uint32(v0):], uint32(v1))
		if v1 != 0 {
			goto l0
		}
		t8 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(65536)):]))
		binary.LittleEndian.PutUint32(mem[uint32(i32(65536)):], uint32(t8&i32_rotl(int32(-2), v3)))
	}
l0:
	m.g0 = v2 + int32(16)
}
func (m *Module) Xmalloc(v0 int32) int32 {
	mem := m.memory
	var v1, v2, v3, v4 int32
	{
		if v0 <= int32(0) {
			goto l0
		}
		v2 = (v0 + int32(19)) & int32(-16)
		t0 := m.fn4(v2)
		v1 = t0
		if v1 == 0 {
			var p1 int32
			if uint32(v0) >= uint32(int32(237)) {
				v0 = int32(bits.LeadingZeros32(uint32(v2)))
				p1 = (i32_shr_u(int32(0x7ffffff), v0) + v2) & i32_shr_s(int32(-0x8000000), v0)
			} else {
				p1 = v2
			}
			v1 = int32(uint32(p1+int32(65555)) >> 16)
			t2 := int32(memory_grow(&m.memory, &m.memBacking, int64(v1), m.maxMem))
			mem = m.memory
			v0 = t2
			if v0 == int32(-1) {
				goto l0
			}
			v1 = (v0 + v1) << 16
			t3 := v1
			v0 = v0 << 16
			t4 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(67240)):]))
			var p5 int32
			if v0 == t4 {
				p5 = 1
			}
			v3 = p5
			p6 := int32(12)
			if v3 != 0 {
				p6 = int32(-4)
			}
			v0 = p6 + v0
			if t3-v0 >= int32(20) {
				v4 = v1 - int32(4)
				binary.LittleEndian.PutUint32(mem[uint32(v4):], uint32(i32(0)))
				t8 := v0
				var p7 int32
				if v3 != 0 {
					t9 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
					p7 = t9 & int32(15)
				} else {
					p7 = int32(0)
				}
				binary.LittleEndian.PutUint32(mem[uint32(t8):], uint32(p7|(v4-v0)))
				m.fn1(v0)
				binary.LittleEndian.PutUint32(mem[uint32(i32(67240)):], uint32(v1))
			}
			t10 := m.fn4(v2)
			v1 = t10
			if v1 == 0 {
				goto l1
			}
		}
		m.fn2(v1)
		t11 := int32(binary.LittleEndian.Uint32(mem[uint32(v1):]))
		t12 := v1
		v0 = t11
		binary.LittleEndian.PutUint32(mem[uint32(t12):], uint32(v0&int32(-2)))
		v0 = v1 + v0&int32(-16)
		t13 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
		binary.LittleEndian.PutUint32(mem[uint32(v0):], uint32(t13&int32(-3)))
		t14 := m.fn5(v1, v2)
		v0 = t14
		if v0 != 0 {
			m.fn1(v0)
		}
		v3 = v1 + int32(4)
		if v3&int32(15) != 0 {
			goto l1
		}
	}
l0:
	return v3
l1:
	panic("unreachable")
}
func (m *Module) fn4(v0 int32) int32 {
	mem := m.memory
	var v1, v2, v3 int32
	t0 := m.g0
	v1 = t0 - int32(16)
	m.g0 = v1
	m.fn6(v0, int32(0), v1+int32(12), v1+int32(8))
	{
		t1 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v1))+12:]))
		v0 = t1
		t2 := int32(binary.LittleEndian.Uint32(mem[uint32(v0<<2+int32(65540)):]))
		t3 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v1))+8:]))
		v2 = t2 & i32_shl(int32(-1), t3)
		if v2 == 0 {
			t4 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(65536)):]))
			v0 = t4 & i32_shl(int32(-1), v0+int32(1))
			if v0 == 0 {
				goto l0
			}
			v0 = int32(bits.TrailingZeros32(uint32(v0)))
			t5 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v0<<2))+65540:]))
			v2 = t5
		}
		t6 := int32(binary.LittleEndian.Uint32(mem[uint32(v0<<6+int32(bits.TrailingZeros32(uint32(v2)))<<2+int32(65640)):]))
		v3 = t6
	}
l0:
	m.g0 = v1 + int32(16)
	return v3
}
func (m *Module) fn5(v0, v1 int32) int32 {
	mem := m.memory
	var v2, v3, v4 int32
	{
		t0 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
		v2 = t0
		v3 = v2&int32(-16) - v1
		if uint32(v3) >= uint32(int32(16)) {
			if v1&int32(15) != 0 {
				panic("unreachable")
			}
			binary.LittleEndian.PutUint32(mem[uint32(v0):], uint32(v2&int32(15)|v1))
			v4 = v0 + v1
			binary.LittleEndian.PutUint32(mem[uint32(v4):], uint32(v3))
		}
		return v4
	}
}
func (m *Module) fn6(v0, v1, v2, v3 int32) {
	mem := m.memory
	var v4, v5 int32
	{
		if uint32(v0) <= uint32(int32(255)) {
			if v0&int32(15) != 0 {
				panic("unreachable")
			}
			binary.LittleEndian.PutUint32(mem[uint32(v2):], uint32(i32(0)))
			binary.LittleEndian.PutUint32(mem[uint32(v3):], uint32(int32(uint32(v0)>>4)))
			return
		}
		t0 := v2
		v4 = int32(bits.LeadingZeros32(uint32(v0)))
		binary.LittleEndian.PutUint32(mem[uint32(t0):], uint32(int32(24)-v4))
		t1 := v3
		v5 = i32_shr_u(v0, int32(27)-v4) & int32(15)
		binary.LittleEndian.PutUint32(mem[uint32(t1):], uint32(v5))
		{
			t2 := v1
			var p3 int32
			if i32_shl(v0, v4)&int32(0x7ffffff) == 0 {
				p3 = 1
			}
			if t2|p3 != 0 {
				return
			}
			t4 := v3
			v0 = v5 + int32(1)
			binary.LittleEndian.PutUint32(mem[uint32(t4):], uint32(v0))
			if v0 != int32(16) {
				return
			}
			binary.LittleEndian.PutUint32(mem[uint32(v3):], uint32(i32(0)))
			binary.LittleEndian.PutUint32(mem[uint32(v2):], uint32(int32(25)-v4))
		}
		return
	}
}
func (m *Module) Xrealloc(v0, v1 int32) int32 {
	mem := m.memory
	var v2, v3, v4, v5, v6, v7 int32
	if v0 == 0 {
		t0 := m.Xmalloc(v1)
		mem = m.memory
		return t0
	}
	if v1 == 0 {
		m.Xfree(v0)
		return int32(0)
	}
	{
		if v1 < int32(0) {
			goto l0
		}
		if v0&int32(15) != 0 {
			goto l1
		}
		v2 = v0 - int32(4)
		t1 := int32(binary.LittleEndian.Uint32(mem[uint32(v2):]))
		v3 = t1
		if v3&int32(1) != 0 {
			goto l1
		}
		v4 = (v1 + int32(19)) & int32(-16)
		t2 := v4
		v3 = v3 & int32(-16)
		if uint32(t2) <= uint32(v3) {
			t3 := m.fn5(v2, v4)
			v1 = t3
			if v1 == 0 {
				goto l2
			}
			m.fn1(v1)
			goto l2
		}
		v6 = v2 + v3
		t4 := int32(binary.LittleEndian.Uint32(mem[uint32(v6):]))
		v7 = t4
		var p5 int32
		if v7&int32(1) == 0 {
			p5 = 1
		}
		var p6 int32
		if uint32(v7&int32(-16)+v3) < uint32(v4) {
			p6 = 1
		}
		if p5|p6 == 0 {
			m.fn2(v6)
			t7 := int32(binary.LittleEndian.Uint32(mem[uint32(v6):]))
			t8 := v2
			v1 = t7&int32(-16) + v3
			t9 := int32(binary.LittleEndian.Uint32(mem[uint32(v2):]))
			binary.LittleEndian.PutUint32(mem[uint32(t8):], uint32(v1|t9&int32(15)))
			v1 = v1 + v2
			t10 := int32(binary.LittleEndian.Uint32(mem[uint32(v1):]))
			binary.LittleEndian.PutUint32(mem[uint32(v1):], uint32(t10&int32(-3)))
			t11 := m.fn5(v2, v4)
			v1 = t11
			if v1 == 0 {
				goto l2
			}
			m.fn1(v1)
			goto l2
		}
		t12 := m.Xmalloc(v1)
		mem = m.memory
		v1 = t12
		if v1 == 0 {
			goto l0
		}
		v5 = v3 - int32(4)
		if v5 != 0 {
			memory_copy(mem, uint32(v1), uint32(v0), uint32(v5))
		}
		m.Xfree(v0)
		v5 = v1
	}
l0:
	return v5
l1:
	panic("unreachable")
l2:
	return v0
}
func (m *Module) Xmemalign(v0, v1 int32) int32 {
	mem := m.memory
	var v2, v3, v4 int32
	{
		var p0 int32
		if int32(bits.OnesCount32(uint32(v0))) != int32(1) {
			p0 = 1
		}
		var p1 int32
		if v1 <= int32(0) {
			p1 = 1
		}
		if p0|p1 != 0 {
			goto l0
		}
		if uint32(v0) <= uint32(int32(16)) {
			t2 := m.Xmalloc(v1)
			mem = m.memory
			return t2
		}
		v4 = v0 + v1
		t3 := m.Xmalloc(v4)
		mem = m.memory
		v2 = t3
		if v2 == 0 {
			goto l0
		}
		if v2&int32(15) != 0 {
			goto l1
		}
		v3 = v2 - int32(4)
		t4 := int32(binary.LittleEndian.Uint32(mem[uint32(v3):]))
		if t4&int32(1) != 0 {
			goto l1
		}
		t5 := v0
		v0 = (v0 + v2 - int32(1)) & (int32(0) - v0)
		p6 := int32(0)
		if v0-v2 < int32(16) {
			p6 = t5
		}
		p7 := int32(0)
		if uint32(v0) > uint32(v2) {
			p7 = p6
		}
		v0 = p7 + v0
		if uint32(v0+v1) > uint32(v2+v4) {
			goto l1
		}
		{
			if uint32(v0) <= uint32(v2) {
				v0 = v3
				goto l2
			}
			t8 := m.fn5(v3, v0-v2)
			v0 = t8
			if v0 == 0 {
				goto l1
			}
			m.fn1(v3)
		}
	l2:
		t9 := m.fn5(v0, (v1+int32(19))&int32(-16))
		v1 = t9
		if v1 != 0 {
			m.fn1(v1)
		}
		v3 = v0 + int32(4)
		if v3&int32(15) != 0 {
			goto l1
		}
	}
l0:
	return v3
l1:
	panic("unreachable")
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(m)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(mem[addr:])
	}
	_ = mem[uint64(addr)+3]
	val := *(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr)))
	if big {
		return bits.ReverseBytes32(val)
	}
	return val
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	_ = mem[uint64(addr)+3]
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func load32u[T uint32 | uint64](mem []byte, addr T) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(mem[addr:])
	}
	val := *(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr)))
	if big {
		return bits.ReverseBytes32(val)
	}
	return val
}

//go:nosplit
func store32u[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i32_shl(x, y int32) int32 {
	return x << (y & 31)
}

//go:nosplit
func i32_shr_s(x, y int32) int32 {
	return x >> (y & 31)
}

//go:nosplit
func i32_shr_u(x, y int32) int32 {
	return int32(uint32(x) >> (y & 31))
}

//go:nosplit
func i32_rotl(x, y int32) int32 {
	return int32(bits.RotateLeft32(uint32(x), int(y)))
}

// Grows the memory *mem by delta pages, up to max, and returns its old size
// in pages, or -1. *back is the memory's backing array: *mem is its prefix,
// with its capacity cut to its length, so no slice of the memory reaches
// past its end, and back's bytes past the memory's end are zero. Growth
// within back is in place: no copy, no allocation. Past it, the memory moves
// to a new backing array of twice the size, at least what the growth needs,
// at most max pages.
func memory_grow(mem, back *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	size := int(new << 16)
	if size > cap(*back) {
		n := int(min(uint64(cap(*back))>>15, uint64(max)) << 16)
		if n < size {
			n = size
		}
		b := make([]byte, n)
		copy(b, buf)
		*back = b
	}
	*mem = (*back)[:size:size]
	return int64(old)
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	mem = mem[:len(mem):len(mem)]
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], mem[z:w])
}
