// Code generated by wasm2go. DO NOT EDIT.

package functions9

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/memgrow/internal/instance"
	"math"
	"math/bits"
)

func Fn3(m *instance.Module) int32 {
	t0 := int32(memory_grow(&m.Memory, int64(int32(1)), m.MaxMem))
	return t0
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	*mem = append(buf, make([]byte, int(new<<16)-len)...)
	return int64(old)
}
