// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
}

func New() *Module {
	m := new(Module)
	return m
}
func (m *Module) Xfactorial(v0 int32) int32 {
	var p0 int32
	if v0 <= int32(1) {
		p0 = int32(1)
	} else {
		t1 := m.Xfactorial(v0 - int32(1))
		p0 = v0 * t1
	}
	return p0
}
func (m *Module) Xis_even(v0 int32) int32 {
	var p0 int32
	if v0 == 0 {
		p0 = int32(1)
	} else {
		t1 := m.Xis_odd(v0 - int32(1))
		p0 = t1
	}
	return p0
}
func (m *Module) Xis_odd(v0 int32) int32 {
	var p0 int32
	if v0 == 0 {
		p0 = int32(0)
	} else {
		t1 := m.Xis_even(v0 - int32(1))
		p0 = t1
	}
	return p0
}

//go:nosplit
func i32(x int32) int32 { return x }
