// Code generated by wasm2go. DO NOT EDIT.

package functions47

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop22(m *instance.Module, v0, v1 int64) int64 {
	return int64(math.Float64bits(math.Copysign(math.Float64frombits(uint64(v0)), math.Float64frombits(uint64(v1)))))
}
