// Code generated by wasm2go. DO NOT EDIT.

//go:build 386 || amd64 || arm64 || loong64 || ppc64le || wasm

package functions1

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/instance"
	"unsafe"
)

func Xcopy(m *instance.Module, v0 int32) int32 {
	mem := m.Memory
	var v1 int32
	_ = int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(v0))+4+3]), -3)))
	v1 = v0
	t1 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(uint32(v1)))))
	return t1
}
