package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// A module that needs no host function still gets its output file, so that
// a file left by an earlier build (with methods the module now defines
// itself) never stays behind.
func Test_noImports(t *testing.T) {
	out := filepath.Join(t.TempDir(), "libc.go")
	if err := os.WriteFile(out, []byte("stale"), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "run", ".", "-pkg", "fib", "-wasm", "../testdata/fib/fib.wasm", "-o", out)
	if b, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("%v\n%s", err, b)
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	const want = "// Code generated by libc-gen. DO NOT EDIT.\n\n" +
		"// Input to wasm2go -provided, which copies these declarations into its\n" +
		"// translation; this file is not built.\n\n//go:build ignore\n\npackage fib\n"
	if string(b) != want {
		t.Errorf("got %q, want %q", b, want)
	}
}

// Go's math package computes different bits on different CPUs, so C math
// functions are musl's, compiled into the module, with one exception: fma,
// whose result IEEE 754 defines exactly, calls math.FMA. No other host
// function may use the math package except for its bit conversions.
func Test_mathHostFunctions(t *testing.T) {
	bits := map[string]bool{"Float32bits": true, "Float32frombits": true, "Float64bits": true, "Float64frombits": true}
	files, err := filepath.Glob("go/*.go")
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range files {
		if strings.HasSuffix(name, "_test.go") || filepath.Base(name) == "libc.go" {
			continue
		}
		f, err := parser.ParseFile(token.NewFileSet(), name, nil, 0)
		if err != nil {
			t.Fatal(err)
		}
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}
			ast.Inspect(fd, func(n ast.Node) bool {
				sel, ok := n.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				if id, ok := sel.X.(*ast.Ident); !ok || id.Name != "math" || bits[sel.Sel.Name] {
					return true
				}
				if fd.Name.Name != "fma" || sel.Sel.Name != "FMA" {
					t.Errorf("%s: %s calls math.%s", name, fd.Name.Name, sel.Sel.Name)
				}
				return true
			})
		}
	}
}
