// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
	"math/bits"
)

// A Module must be created by New and never copied.
// Calls through its function tables are compiled into direct calls
// on the receiver, which must be the Module New filled the tables for,
// and code outside the translated module must not change the tables.
type Module struct {
	t0       []any
	t1       []any
	elements [][]any
	memory   []byte
	maxMem   int64
	_env     Xenv
}

func New(v0 Xenv) *Module {
	m := new(Module)
	m._env = v0
	m.t0 = make([]any, 3)
	m.t1 = make([]any, 1)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	m.elements = [][]any{{m.fn3, fn4, m.fn5}, {fn4}}
	table_init(m.t0, m.elements[0], i32(0), 0, len(m.elements[0]))
	m.elements[0] = nil
	table_init(m.t1, m.elements[1], i32(0), 0, len(m.elements[1]))
	m.elements[1] = nil
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xenv = interface {
	Xgrow() int32
}
type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) fn0() int32 {
	return m._env.Xgrow()
}
func (m *Module) fn3() int32 {
	t0 := int32(memory_grow(&m.memory, int64(i32(1)), m.maxMem))
	return t0
}
func fn4() int32 {
	return i32(0)
}
func (m *Module) fn5() int32 {
	t0 := m.fn3()
	return t0
}
func (m *Module) Xdirect() int32 {
	mem := m.memory
	var v0 int32
	store32(mem, uint32(i32(0)), uint32(i32(1)))
	t0 := m.fn5()
	mem = m.memory
	v0 = t0
	store32(mem, uint32(v0*i32(65536)), uint32(i32(99)))
	t1 := int32(load32(mem, uint32(v0*i32(65536))))
	return t1
}
func (m *Module) Xclosed(v0 int32) int32 {
	mem := m.memory
	var v1 int32
	store32(mem, uint32(i32(0)), uint32(i32(1)))
	var t0 int32
	switch t2 := uint(v0); t2 {
	case 0:
		t0 = m.fn3()
		mem = m.memory
	case 1:
		t0 = fn4()
	case 2:
		t0 = m.fn5()
		mem = m.memory
	default:
		t0 = m.t0[t2].(func() int32)()
		mem = m.memory
	}
	v1 = t0
	store32(mem, uint32(v1*i32(65536)), uint32(i32(99)))
	t1 := int32(load32(mem, uint32(v1*i32(65536))))
	return t1
}
func (m *Module) Xopen() int32 {
	mem := m.memory
	var v0 int32
	store32(mem, uint32(i32(0)), uint32(i32(1)))
	t0 := m.t1[uint(i32(0))].(func() int32)()
	mem = m.memory
	v0 = t0
	store32(mem, uint32(v0*i32(65536)), uint32(i32(99)))
	t1 := int32(load32(mem, uint32(v0*i32(65536))))
	return t1
}
func (m *Module) Xhost() int32 {
	mem := m.memory
	var v0 int32
	store32(mem, uint32(i32(0)), uint32(i32(1)))
	t0 := m.fn0()
	mem = m.memory
	v0 = t0
	store32(mem, uint32(v0*i32(65536)), uint32(i32(99)))
	t1 := int32(load32(mem, uint32(v0*i32(65536))))
	return t1
}
func (m *Module) Xprovided() int32 {
	mem := m.memory
	var v0 int32
	store32(mem, uint32(i32(0)), uint32(i32(1)))
	t0 := m._pgrow()
	mem = m.memory
	v0 = t0
	store32(mem, uint32(v0*i32(65536)), uint32(i32(99)))
	t1 := int32(load32(mem, uint32(v0*i32(65536))))
	return t1
}
func (m *Module) Xpeek(v0 int32) int32 {
	mem := m.memory
	store32(mem, uint32(i32(0)), uint32(i32(1)))
	t0 := m._ppeek(v0)
	t1 := int32(load32(mem, uint32(i32(0))))
	return t0 + t1
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}
func (m *Module) Xtable() *[]any {
	return &m.t1
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	return binary.LittleEndian.Uint32(mem[addr:])
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	binary.LittleEndian.PutUint32(mem[addr:], val)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	*mem = append(buf, make([]byte, int(new<<16)-len)...)
	return int64(old)
}

func table_init[T1, T2, T3 int | int32 | int64](tab, elems []any, dest T1, src T2, n T3) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(tab[x:y], elems[z:w])
}
