// Code generated by wasm2go. DO NOT EDIT.

//go:build 386 || amd64 || arm64 || loong64 || ppc64le || wasm

package wasm2go

import (
	"math"
	"math/bits"
	"runtime"
)

// A Module must be created by New and never copied.
// Calls through its function tables are compiled into direct calls
// on the receiver, which must be the Module New filled the tables for,
// and code outside the translated module must not change the tables.
type Module struct {
	t0         []any
	elements   [][]any
	memory     []byte
	memBacking []byte
	maxMem     int64
	g0         int32
	g1         int32
	stackUsed  int64
}

func New() *Module {
	m := new(Module)
	m.t0 = make([]any, 2)
	m.maxMem = 65536
	m.memBacking = make([]byte, 65536)
	m.memory = m.memBacking
	m.elements = [][]any{{m.fn4, fn0}}
	table_init(m.t0, m.elements[0], i32(0), 0, len(m.elements[0]))
	m.elements[0] = nil
	m.g0 = i32(65536)
	m.g1 = i32(0)
	return m
}

// MemoryMax is the most bytes the module's memory can grow to
// through its own memory.grow: its declared maximum.
func (m *Module) MemoryMax() int64 { return 4294967296 }

// UseMemory moves the module's memory to the start of buf's backing array,
// where it keeps its size and contents and grows in place, without
// copying or allocating, as far as buf's capacity allows (past it, it moves
// to a new array in the Go heap). buf's bytes past the memory's size must
// be zero, and nothing else may write to them. UseMemory returns false,
// and leaves the memory where it is, when buf's capacity is less than the
// memory's size (a nil buf included). Slices of the memory taken before
// the call are stale after it, as after the memory grows.
func (m *Module) UseMemory(buf []byte) bool {
	n := len(m.memory)
	if cap(buf) < n {
		return false
	}
	buf = buf[:cap(buf)]
	copy(buf, m.memory)
	m.memBacking = buf
	m.memory = buf[:n:n]
	return true
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory Module

func (m *wasmMemory) Slice() *[]byte { return &m.memory }

func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow(&m.memory, &m.memBacking, delta, max)
}
func fn0(v0 int32) int32 {
	return v0
}
func (m *Module) Xsp() int32 {
	t0 := m.g0
	return t0
}
func (m *Module) XcallsLeaf(v0 int32) int32 {
	_ = fn0(v0)
	t1 := m.g0
	return t1
}
func (m *Module) fn3(v0 int32) int32 {
	if m.stackUsed += 1006; m.stackUsed > 201326592 {
		panic("call stack exhausted")
	}
	t0 := m.g0
	m.g0 = t0 - int32(560)
	t1 := m.g0
	if t1 < int32(0xc000) {
		panic("unreachable")
	}
	var p2 int32
	{
		{
			if v0 == 0 {
				goto l0
			}
			t3 := m.fn3(v0 - int32(1))
			t4 := m.g0
			m.g0 = t4 + int32(560)
			{
				m.stackUsed -= 1006
				return t3
			}
		}
	l0:
		t5 := m.g0
		p2 = t5
	}
	t6 := m.g0
	m.g0 = t6 + int32(560)
	{
		m.stackUsed -= 1006
		return p2
	}
}
func (m *Module) fn4(v0 int32) int32 {
	if m.stackUsed += 1006; m.stackUsed > 201326592 {
		panic("call stack exhausted")
	}
	t0 := m.g0
	m.g0 = t0 - int32(560)
	t1 := m.g0
	if t1 < int32(0xc000) {
		panic("unreachable")
	}
	var p2 int32
	{
		var p3 int32
		if v0 == 0 {
			t4 := m.g0
			p3 = t4
		} else {
			var t5 int32
			switch t7 := uint(i32(0)); t7 {
			case 0:
				t5 = m.fn4(v0 - int32(1))
			case 1:
				t5 = fn0(v0 - int32(1))
			default:
				t5 = m.t0[t7].(func(int32) int32)(v0 - int32(1))
			}
			p3 = t5
		}
		p2 = p3
	}
	t6 := m.g0
	m.g0 = t6 + int32(560)
	{
		m.stackUsed -= 1006
		return p2
	}
}
func (m *Module) fn5(v0 int32) (int32, int32) {
	if m.stackUsed += 1006; m.stackUsed > 201326592 {
		panic("call stack exhausted")
	}
	var v1, v2 int32
	t0 := m.g0
	m.g0 = t0 - int32(560)
	t1 := m.g0
	if t1 < int32(0xc000) {
		panic("unreachable")
	}
	var p2 int32
	var p3 int32
	{
		if v0 == 0 {
			t4 := m.g0
			t5 := m.g0
			t6 := v0
			m.g0 = t5 + int32(560)
			{
				m.stackUsed -= 1006
				return t4, t6
			}
		}
		t7, t8 := m.fn5(v0 - int32(1))
		v2 = t8
		v1 = t7
		t9 := v1
		t10 := v2 + int32(1)
		switch v0 {
		default:
			p2, p3 = t9, t10
			{
				t11 := m.g0
				m.g0 = t11 + int32(560)
				{
					m.stackUsed -= 1006
					return p2, p3
				}
			}
		}
	}
}
func (m *Module) fn6(v0 int32) {
	if m.stackUsed += 1006; m.stackUsed > 201326592 {
		panic("call stack exhausted")
	}
	t0 := m.g0
	m.g0 = t0 - int32(560)
	t1 := m.g0
	if t1 < int32(0xc000) {
		panic("unreachable")
	}
	{
		t2 := m.g1
		m.g1 = t2 + int32(1)
		if v0 == 0 {
			t3 := m.g0
			m.g0 = t3 + int32(560)
			{
				m.stackUsed -= 1006
				return
			}
		}
		m.fn6(v0 - int32(1))
	}
	t4 := m.g0
	m.g0 = t4 + int32(560)
	m.stackUsed -= 1006
}
func (m *Module) fn7(v0 int32) int32 {
	m.g1 = int32(0)
	m.fn6(v0)
	t0 := m.g0
	return t0
}
func (m *Module) fn8(v0 int32) int32 {
	if m.stackUsed += 1006; m.stackUsed > 201326592 {
		panic("call stack exhausted")
	}
	t0 := m.g0
	m.g0 = t0 - int32(560)
	t1 := m.g0
	if t1 < int32(0xc000) {
		panic("unreachable")
	}
	var p2 int32
	{
		t3 := m.g1
		m.g1 = t3 + int32(1)
		t4 := m.fn8(v0)
		p2 = t4 + int32(1)
	}
	t5 := m.g0
	m.g0 = t5 + int32(560)
	{
		m.stackUsed -= 1006
		return p2
	}
}
func (m *Module) fn9() int32 {
	m.g1 = int32(0)
	t0 := m.fn8(i32(0))
	return t0
}
func (m *Module) X__stack_pointer() *int32 {
	return &m.g0
}
func (m *Module) Xcount() *int32 {
	return &m.g1
}
func (m *Module) Xdown(v0 int32) int32 {
	defer func(used int64) {
		m.stackUsed = used
	}(m.stackUsed)
	return m.fn3(v0)
}
func (m *Module) Xforever() int32 {
	defer func(used int64) {
		m.stackUsed = used
	}(m.stackUsed)
	return m.fn9()
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(m)
}
func (m *Module) Xpair(v0 int32) (int32, int32) {
	defer func(used int64) {
		m.stackUsed = used
	}(m.stackUsed)
	return m.fn5(v0)
}
func (m *Module) XviaTable(v0 int32) int32 {
	defer func(used int64) {
		m.stackUsed = used
	}(m.stackUsed)
	return m.fn4(v0)
}
func (m *Module) Xwalk(v0 int32) int32 {
	defer func(used int64) {
		m.stackUsed = used
	}(m.stackUsed)
	return m.fn7(v0)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func i32(x int32) int32 { return x }

// Grows the memory *mem by delta pages, up to max, and returns its old size
// in pages, or -1. *back is the memory's backing array: *mem is its prefix,
// with its capacity cut to its length, so no slice of the memory reaches
// past its end, and back's bytes past the memory's end are zero. Growth
// within back is in place: no copy, no allocation. Past it, the memory moves
// to a new backing array of twice the size, at least what the growth needs,
// at most max pages.
func memory_grow(mem, back *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	size := int(new << 16)
	if size > cap(*back) {
		n := int(min(uint64(cap(*back))>>15, uint64(max)) << 16)
		if n < size {
			n = size
		}
		b := make([]byte, n)
		copy(b, buf)
		*back = b
	}
	*mem = (*back)[:size:size]
	return int64(old)
}

func table_init[T1, T2, T3 int | int32 | int64](tab, elems []any, dest T1, src T2, n T3) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(tab[x:y], elems[z:w])
}
