// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && arm64 && go1.27 && !go1.28

package functions56

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"math/bits"
	"simd/archsimd"
)

type vec128 = archsimd.Uint32x4

func Xop100(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := archsimd.BroadcastUint32x4(math.Float32bits((t0)))
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := t1.SetElem(1, math.Float32bits((t2)))
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := t3.SetElem(2, math.Float32bits((t4)))
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := t5.SetElem(3, math.Float32bits((t6)))
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := archsimd.BroadcastUint32x4(math.Float32bits((t8)))
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := t9.SetElem(1, math.Float32bits((t10)))
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := t11.SetElem(2, math.Float32bits((t12)))
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := t13.SetElem(3, math.Float32bits((t14)))
	t16 := t7.BitsToFloat32().NotEqual(t15.BitsToFloat32()).ToInt32x4().ToBits()
	v2 = t16
	t17 := v2
	t18 := int32(t17.GetElem(0))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.GetElem(1))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.GetElem(2))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.GetElem(3))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}

//go:nosplit
func i64_rotl(x, y int64) int64 {
	return int64(bits.RotateLeft64(uint64(x), int(y)))
}
