// Code generated by wasm2go. DO NOT EDIT.

package functions35

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop34(m *instance.Module, v0, v1 int64) int64 {
	t0 := i64_trunc_f32_s(math.Float32frombits(uint32(int32(v0))))
	return t0
}

//go:nosplit
func i64_trunc_f32_s(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	}
	return int64(x)
}
