// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package wasm2go

import (
	"encoding/binary"
	"math"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func (m *Module) Xop91(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t20.F1))))))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t23.F2))))))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t26.F3))))))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop92(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 - t15.F0), float32(t7.F1 - t15.F1), float32(t7.F2 - t15.F2), float32(t7.F3 - t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t20.F1))))))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t23.F2))))))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t26.F3))))))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop93(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 * t15.F0), float32(t7.F1 * t15.F1), float32(t7.F2 * t15.F2), float32(t7.F3 * t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t20.F1))))))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t23.F2))))))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t26.F3))))))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop94(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 / t15.F0), float32(t7.F1 / t15.F1), float32(t7.F2 / t15.F2), float32(t7.F3 / t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t20.F1))))))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t23.F2))))))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t26.F3))))))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop95(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{math.Float32frombits(lane_canon32(math.Float32bits(min(t7.F0, t15.F0)))), math.Float32frombits(lane_canon32(math.Float32bits(min(t7.F1, t15.F1)))), math.Float32frombits(lane_canon32(math.Float32bits(min(t7.F2, t15.F2)))), math.Float32frombits(lane_canon32(math.Float32bits(min(t7.F3, t15.F3))))}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits(t17.F0))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits(t20.F1))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits(t23.F2))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits(t26.F3))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop96(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{math.Float32frombits(lane_canon32(math.Float32bits(max(t7.F0, t15.F0)))), math.Float32frombits(lane_canon32(math.Float32bits(max(t7.F1, t15.F1)))), math.Float32frombits(lane_canon32(math.Float32bits(max(t7.F2, t15.F2)))), math.Float32frombits(lane_canon32(math.Float32bits(max(t7.F3, t15.F3))))}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits(t17.F0))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits(t20.F1))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits(t23.F2))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits(t26.F3))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop97(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{lane_pminf32(t7.F0, t15.F0), lane_pminf32(t7.F1, t15.F1), lane_pminf32(t7.F2, t15.F2), lane_pminf32(t7.F3, t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits(t17.F0))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits(t20.F1))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits(t23.F2))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits(t26.F3))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop98(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{lane_pmaxf32(t7.F0, t15.F0), lane_pmaxf32(t7.F1, t15.F1), lane_pmaxf32(t7.F2, t15.F2), lane_pmaxf32(t7.F3, t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(math.Float32bits(t17.F0))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits(t20.F1))
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(math.Float32bits(t23.F2))
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(math.Float32bits(t26.F3))
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop99(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128{lane_mask32(t7.F0 == t15.F0), lane_mask32(t7.F1 == t15.F1), lane_mask32(t7.F2 == t15.F2), lane_mask32(t7.F3 == t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(t17.L0)
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.L1)
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.L2)
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.L3)
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop100(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128{lane_mask32(t7.F0 != t15.F0), lane_mask32(t7.F1 != t15.F1), lane_mask32(t7.F2 != t15.F2), lane_mask32(t7.F3 != t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(t17.L0)
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.L1)
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.L2)
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.L3)
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop101(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128{lane_mask32(t7.F0 < t15.F0), lane_mask32(t7.F1 < t15.F1), lane_mask32(t7.F2 < t15.F2), lane_mask32(t7.F3 < t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(t17.L0)
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.L1)
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.L2)
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.L3)
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop102(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128{lane_mask32(t7.F0 > t15.F0), lane_mask32(t7.F1 > t15.F1), lane_mask32(t7.F2 > t15.F2), lane_mask32(t7.F3 > t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(t17.L0)
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.L1)
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.L2)
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.L3)
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop103(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128{lane_mask32(t7.F0 <= t15.F0), lane_mask32(t7.F1 <= t15.F1), lane_mask32(t7.F2 <= t15.F2), lane_mask32(t7.F3 <= t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(t17.L0)
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.L1)
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.L2)
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.L3)
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop104(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128{lane_mask32(t7.F0 >= t15.F0), lane_mask32(t7.F1 >= t15.F1), lane_mask32(t7.F2 >= t15.F2), lane_mask32(t7.F3 >= t15.F3)}
	v2 = t16
	t17 := v2
	t18 := int32(t17.L0)
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(t20.L1)
	t22 := t19 | int64(uint32(t21))<<32
	t23 := v2
	t24 := int32(t23.L2)
	t25 := int64(uint32(t24))
	t26 := v2
	t27 := int32(t26.L3)
	return t22 + i64_rotl(t25|int64(uint32(t27))<<32, int64(17))
}
func (m *Module) Xop105(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{float32(math.Sqrt(float64(t7.F0))), float32(math.Sqrt(float64(t7.F1))), float32(math.Sqrt(float64(t7.F2))), float32(math.Sqrt(float64(t7.F3)))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t9.F0))))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t12.F1))))))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t15.F2))))))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t18.F3))))))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop106(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{float32(math.Ceil(float64(t7.F0))), float32(math.Ceil(float64(t7.F1))), float32(math.Ceil(float64(t7.F2))), float32(math.Ceil(float64(t7.F3)))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t9.F0))))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t12.F1))))))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t15.F2))))))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t18.F3))))))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop107(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{float32(math.Floor(float64(t7.F0))), float32(math.Floor(float64(t7.F1))), float32(math.Floor(float64(t7.F2))), float32(math.Floor(float64(t7.F3)))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t9.F0))))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t12.F1))))))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t15.F2))))))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t18.F3))))))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop108(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{float32(math.Trunc(float64(t7.F0))), float32(math.Trunc(float64(t7.F1))), float32(math.Trunc(float64(t7.F2))), float32(math.Trunc(float64(t7.F3)))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t9.F0))))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t12.F1))))))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t15.F2))))))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t18.F3))))))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop109(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{float32(math.RoundToEven(float64(t7.F0))), float32(math.RoundToEven(float64(t7.F1))), float32(math.RoundToEven(float64(t7.F2))), float32(math.RoundToEven(float64(t7.F3)))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t9.F0))))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t12.F1))))))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t15.F2))))))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t18.F3))))))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop110(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{math.Float32frombits(math.Float32bits(t7.F0) &^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F1) &^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F2) &^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F3) &^ (1 << 31))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits(t9.F0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits(t12.F1))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits(t15.F2))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits(t18.F3))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop111(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{math.Float32frombits(math.Float32bits(t7.F0) ^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F1) ^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F2) ^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F3) ^ (1 << 31))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits(t9.F0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits(t12.F1))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits(t15.F2))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits(t18.F3))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop112(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 + t7.D0), float64(t3.D1 + t7.D1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop113(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 - t7.D0), float64(t3.D1 - t7.D1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop114(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 * t7.D0), float64(t3.D1 * t7.D1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop115(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 / t7.D0), float64(t3.D1 / t7.D1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop116(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{math.Float64frombits(lane_canon64(math.Float64bits(min(t3.D0, t7.D0)))), math.Float64frombits(lane_canon64(math.Float64bits(min(t3.D1, t7.D1))))}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits(t9.D0))) | uint64(uint32((math.Float64bits(t9.D0))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D1))) | uint64(uint32((math.Float64bits(t11.D1))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop117(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{math.Float64frombits(lane_canon64(math.Float64bits(max(t3.D0, t7.D0)))), math.Float64frombits(lane_canon64(math.Float64bits(max(t3.D1, t7.D1))))}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits(t9.D0))) | uint64(uint32((math.Float64bits(t9.D0))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D1))) | uint64(uint32((math.Float64bits(t11.D1))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop118(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{lane_pminf64(t3.D0, t7.D0), lane_pminf64(t3.D1, t7.D1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits(t9.D0))) | uint64(uint32((math.Float64bits(t9.D0))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D1))) | uint64(uint32((math.Float64bits(t11.D1))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop119(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{lane_pmaxf64(t3.D0, t7.D0), lane_pmaxf64(t3.D1, t7.D1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits(t9.D0))) | uint64(uint32((math.Float64bits(t9.D0))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D1))) | uint64(uint32((math.Float64bits(t11.D1))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop120(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128{uint32(lane_mask64(t3.D0 == t7.D0)), uint32((lane_mask64(t3.D0 == t7.D0)) >> 32), uint32(lane_mask64(t3.D1 == t7.D1)), uint32((lane_mask64(t3.D1 == t7.D1)) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop121(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128{uint32(lane_mask64(t3.D0 != t7.D0)), uint32((lane_mask64(t3.D0 != t7.D0)) >> 32), uint32(lane_mask64(t3.D1 != t7.D1)), uint32((lane_mask64(t3.D1 != t7.D1)) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop122(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128{uint32(lane_mask64(t3.D0 < t7.D0)), uint32((lane_mask64(t3.D0 < t7.D0)) >> 32), uint32(lane_mask64(t3.D1 < t7.D1)), uint32((lane_mask64(t3.D1 < t7.D1)) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop123(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128{uint32(lane_mask64(t3.D0 > t7.D0)), uint32((lane_mask64(t3.D0 > t7.D0)) >> 32), uint32(lane_mask64(t3.D1 > t7.D1)), uint32((lane_mask64(t3.D1 > t7.D1)) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop124(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128{uint32(lane_mask64(t3.D0 <= t7.D0)), uint32((lane_mask64(t3.D0 <= t7.D0)) >> 32), uint32(lane_mask64(t3.D1 <= t7.D1)), uint32((lane_mask64(t3.D1 <= t7.D1)) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop125(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128{uint32(lane_mask64(t3.D0 >= t7.D0)), uint32((lane_mask64(t3.D0 >= t7.D0)) >> 32), uint32(lane_mask64(t3.D1 >= t7.D1)), uint32((lane_mask64(t3.D1 >= t7.D1)) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop126(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Sqrt(t3.D0), math.Sqrt(t3.D1)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop127(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Ceil(t3.D0), math.Ceil(t3.D1)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop128(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Floor(t3.D0), math.Floor(t3.D1)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop129(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Trunc(t3.D0), math.Trunc(t3.D1)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop130(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.RoundToEven(t3.D0), math.RoundToEven(t3.D1)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t5.D0))))))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t7.D1))))))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop131(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Float64frombits(math.Float64bits(t3.D0) &^ (1 << 63)), math.Float64frombits(math.Float64bits(t3.D1) &^ (1 << 63))}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits(t5.D0))) | uint64(uint32((math.Float64bits(t5.D0))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits(t7.D1))) | uint64(uint32((math.Float64bits(t7.D1))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop132(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Float64frombits(math.Float64bits(t3.D0) ^ (1 << 63)), math.Float64frombits(math.Float64bits(t3.D1) ^ (1 << 63))}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits(t5.D0))) | uint64(uint32((math.Float64bits(t5.D0))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits(t7.D1))) | uint64(uint32((math.Float64bits(t7.D1))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop133(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f32{float32(t3.D0), float32(t3.D1), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t5.F0))))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t8.F1))))))
	t10 := t7 | int64(uint32(t9))<<32
	t11 := v2
	t12 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t11.F2))))))
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t14.F3))))))
	return t10 + i64_rotl(t13|int64(uint32(t15))<<32, int64(17))
}
func (m *Module) Xop134(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f64{float64(t7.F0), float64(t7.F1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))) | uint64(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t11.D1))))))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop135(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := int32(v0) ^ int32(-0x80000000)
	t5 := vec128{t3.L0, t3.L1, uint32((t4)), t3.L3}
	t6 := int32(v1) ^ int32(-0x80000000)
	t7 := vec128{t5.L0, t5.L1, t5.L2, uint32((t6))}
	t8 := vec128f32{float32(int32(t7.L0)), float32(int32(t7.L1)), float32(int32(t7.L2)), float32(int32(t7.L3))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits(t9.F0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits(t12.F1))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits(t15.F2))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits(t18.F3))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop136(v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := int32(v0) ^ int32(-0x80000000)
	t5 := vec128{t3.L0, t3.L1, uint32((t4)), t3.L3}
	t6 := int32(v1) ^ int32(-0x80000000)
	t7 := vec128{t5.L0, t5.L1, t5.L2, uint32((t6))}
	t8 := vec128f32{float32(t7.L0), float32(t7.L1), float32(t7.L2), float32(t7.L3)}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits(t9.F0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits(t12.F1))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits(t15.F2))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits(t18.F3))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop137(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := int32(v0) ^ int32(-0x80000000)
	t5 := vec128{t3.L0, t3.L1, uint32((t4)), t3.L3}
	t6 := int32(v1) ^ int32(-0x80000000)
	t7 := vec128{t5.L0, t5.L1, t5.L2, uint32((t6))}
	t8 := vec128f64{float64(int32(t7.L0)), float64(int32(t7.L1))}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits(t9.D0))) | uint64(uint32((math.Float64bits(t9.D0))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D1))) | uint64(uint32((math.Float64bits(t11.D1))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop138(v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := int32(v0) ^ int32(-0x80000000)
	t5 := vec128{t3.L0, t3.L1, uint32((t4)), t3.L3}
	t6 := int32(v1) ^ int32(-0x80000000)
	t7 := vec128{t5.L0, t5.L1, t5.L2, uint32((t6))}
	t8 := vec128f64{float64(t7.L0), float64(t7.L1)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(uint32(math.Float64bits(t9.D0))) | uint64(uint32((math.Float64bits(t9.D0))>>32))<<32))
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D1))) | uint64(uint32((math.Float64bits(t11.D1))>>32))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop139(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128{uint32(i32_trunc_sat_f32_s(t7.F0)), uint32(i32_trunc_sat_f32_s(t7.F1)), uint32(i32_trunc_sat_f32_s(t7.F2)), uint32(i32_trunc_sat_f32_s(t7.F3))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(t15.L2)
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(t18.L3)
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop140(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128{uint32(i32_trunc_sat_f32_u(t7.F0)), uint32(i32_trunc_sat_f32_u(t7.F1)), uint32(i32_trunc_sat_f32_u(t7.F2)), uint32(i32_trunc_sat_f32_u(t7.F3))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(t15.L2)
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(t18.L3)
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}
func (m *Module) Xop141(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128{uint32(i32_trunc_sat_f64_s(t3.D0)), uint32(i32_trunc_sat_f64_s(t3.D1)), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	t10 := t7 | int64(uint32(t9))<<32
	t11 := v2
	t12 := int32(t11.L2)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L3)
	return t10 + i64_rotl(t13|int64(uint32(t15))<<32, int64(17))
}
func (m *Module) Xop142(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128{uint32(i32_trunc_sat_f64_u(t3.D0)), uint32(i32_trunc_sat_f64_u(t3.D1)), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	t10 := t7 | int64(uint32(t9))<<32
	t11 := v2
	t12 := int32(t11.L2)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L3)
	return t10 + i64_rotl(t13|int64(uint32(t15))<<32, int64(17))
}
func (m *Module) Xop143(v0, v1 int64) int64 {
	var v2, v3 vec128f32
	var _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := vec128f32{math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))) ^ (1 << 31))}
	v2 = t18
	t19 := v2
	t20 := int32(math.Float32bits(t19.F0))
	t21 := int64(uint32(t20))
	t22 := v2
	t23 := int32(math.Float32bits(t22.F1))
	t24 := t21 | int64(uint32(t23))<<32
	t25 := v2
	t26 := int32(math.Float32bits(t25.F2))
	t27 := int64(uint32(t26))
	t28 := v2
	t29 := int32(math.Float32bits(t28.F3))
	return t24 + i64_rotl(t27|int64(uint32(t29))<<32, int64(17))
}
func (m *Module) Xop144(v0, v1 int64) int64 {
	var v2, v3 vec128f32
	var _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := vec128f32{math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))) &^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))) &^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))) &^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))) &^ (1 << 31))}
	v2 = t18
	t19 := v2
	t20 := int32(math.Float32bits(t19.F0))
	t21 := int64(uint32(t20))
	t22 := v2
	t23 := int32(math.Float32bits(t22.F1))
	t24 := t21 | int64(uint32(t23))<<32
	t25 := v2
	t26 := int32(math.Float32bits(t25.F2))
	t27 := int64(uint32(t26))
	t28 := v2
	t29 := int32(math.Float32bits(t28.F3))
	return t24 + i64_rotl(t27|int64(uint32(t29))<<32, int64(17))
}
func (m *Module) Xop145(v0, v1 int64) int64 {
	var _, _ vec128
	var v3 vec128f32
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := (math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))
	t19 := int64(uint32(int32(math.Float32bits(t18))))
	t20 := v3
	t21 := (math.Float32frombits(lane_canon32(math.Float32bits(t20.F1))))
	t22 := t19 | int64(uint32(int32(math.Float32bits(t21))))<<32
	t23 := v3
	t24 := (math.Float32frombits(lane_canon32(math.Float32bits(t23.F2))))
	t25 := int64(uint32(int32(math.Float32bits(t24))))
	t26 := v3
	t27 := (math.Float32frombits(lane_canon32(math.Float32bits(t26.F3))))
	return t22 + i64_rotl(t25|int64(uint32(int32(math.Float32bits(t27))))<<32, int64(17))
}
func (m *Module) Xop146(v0, v1 int64) int64 {
	var q16 *[16]byte
	mem := m.memory
	var _, _ vec128
	var v3 vec128f32
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	q16 = (*[16]byte)(mem[uint64(uint32(int32(32))) : uint64(uint32(int32(32)))+16])
	q16[0] = byte(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))))
	q16[1] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))) >> 8))
	q16[2] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))) >> 16))
	q16[3] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))) >> 24))
	q16[4] = byte(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))))
	q16[5] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))) >> 8))
	q16[6] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))) >> 16))
	q16[7] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))) >> 24))
	q16[8] = byte(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))))
	q16[9] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))) >> 8))
	q16[10] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))) >> 16))
	q16[11] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))) >> 24))
	q16[12] = byte(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))))
	q16[13] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))) >> 8))
	q16[14] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))) >> 16))
	q16[15] = byte((math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))) >> 24))
	t18 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(32))) : uint64(uint32(i32(32)))+8])[:]))
	t19 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(40))) : uint64(uint32(i32(40)))+8])[:]))
	return t18 + i64_rotl(t19, int64(17))
}
func (m *Module) Xop147(v0, v1 int64) int64 {
	var v2, _ vec128
	var v3 vec128f32
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	_ = v3
	t19 := vec128{math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))), math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))), math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))), math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2)))))}
	v2 = t19
	t20 := v2
	t21 := int32(t20.L0)
	t22 := int64(uint32(t21))
	t23 := v2
	t24 := int32(t23.L1)
	t25 := t22 | int64(uint32(t24))<<32
	t26 := v2
	t27 := int32(t26.L2)
	t28 := int64(uint32(t27))
	t29 := v2
	t30 := int32(t29.L3)
	return t25 + i64_rotl(t28|int64(uint32(t30))<<32, int64(17))
}
func (m *Module) Xop148(v0, v1 int64) int64 {
	var v2, _ vec128
	var v3 vec128f32
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := vec128{math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0))))) ^ (lane_u32(0x0)), math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1))))) ^ (lane_u32(0x80000000)), math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2))))) ^ (lane_u32(0x80000000)), math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))) ^ (lane_u32(0x0))}
	v2 = t18
	t19 := v2
	t20 := int32(t19.L0)
	t21 := int64(uint32(t20))
	t22 := v2
	t23 := int32(t22.L1)
	t24 := t21 | int64(uint32(t23))<<32
	t25 := v2
	t26 := int32(t25.L2)
	t27 := int64(uint32(t26))
	t28 := v2
	t29 := int32(t28.L3)
	return t24 + i64_rotl(t27|int64(uint32(t29))<<32, int64(17))
}
func (m *Module) Xop149(v0, v1 int64) int64 {
	var v2, v3 vec128f32
	var _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := math.Float32frombits(uint32(int32(v1)))
	t19 := vec128f32{(t18), (t18), (t18), (t18)}
	t20 := math.Float32frombits(uint32(int32(v0)))
	t21 := vec128f32{t19.F0, (t20), t19.F2, t19.F3}
	t22 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t23 := vec128f32{t21.F0, t21.F1, (t22), t21.F3}
	t24 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t25 := vec128f32{t23.F0, t23.F1, t23.F2, (t24)}
	t26 := vec128f32{lane_pminf32((math.Float32frombits(lane_canon32(math.Float32bits(t17.F0)))), t25.F0), lane_pminf32((math.Float32frombits(lane_canon32(math.Float32bits(t17.F1)))), t25.F1), lane_pminf32((math.Float32frombits(lane_canon32(math.Float32bits(t17.F2)))), t25.F2), lane_pminf32((math.Float32frombits(lane_canon32(math.Float32bits(t17.F3)))), t25.F3)}
	v2 = t26
	t27 := v2
	t28 := int32(math.Float32bits(t27.F0))
	t29 := int64(uint32(t28))
	t30 := v2
	t31 := int32(math.Float32bits(t30.F1))
	t32 := t29 | int64(uint32(t31))<<32
	t33 := v2
	t34 := int32(math.Float32bits(t33.F2))
	t35 := int64(uint32(t34))
	t36 := v2
	t37 := int32(math.Float32bits(t36.F3))
	return t32 + i64_rotl(t35|int64(uint32(t37))<<32, int64(17))
}
func (m *Module) Xop150(v0, v1 int64) int64 {
	var v2, v3 vec128f32
	var _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := vec128f32{(math.Float32frombits(0x3f800000)), (math.Float32frombits(lane_canon32(math.Float32bits(t17.F1)))), (math.Float32frombits(lane_canon32(math.Float32bits(t17.F2)))), (math.Float32frombits(lane_canon32(math.Float32bits(t17.F3))))}
	v2 = t18
	t19 := v2
	t20 := int32(math.Float32bits(t19.F0))
	t21 := int64(uint32(t20))
	t22 := v2
	t23 := int32(math.Float32bits(t22.F1))
	t24 := t21 | int64(uint32(t23))<<32
	t25 := v2
	t26 := int32(math.Float32bits(t25.F2))
	t27 := int64(uint32(t26))
	t28 := v2
	t29 := int32(math.Float32bits(t28.F3))
	return t24 + i64_rotl(t27|int64(uint32(t29))<<32, int64(17))
}
func (m *Module) Xop151(v0, v1 int64) int64 {
	var v2, v3, v4 vec128f32
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 * t15.F0), float32(t7.F1 * t15.F1), float32(t7.F2 * t15.F2), float32(t7.F3 * t15.F3)}
	v3 = t16
	t17 := v3
	t18 := vec128f32{float32(t17.F0 + math.Float32frombits((lane_u32(0xbf800000)))), float32(t17.F1 + math.Float32frombits((lane_u32(0xbf800000)))), float32(t17.F2 + math.Float32frombits((lane_u32(0xbf800000)))), float32(t17.F3 + math.Float32frombits((lane_u32(0xbf800000))))}
	v4 = t18
	t19 := v4
	t20 := vec128f32{math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t19.F0))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t19.F1))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t19.F2))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t19.F3))))) ^ (1 << 31))}
	v2 = t20
	t21 := v2
	t22 := int32(math.Float32bits(t21.F0))
	t23 := int64(uint32(t22))
	t24 := v2
	t25 := int32(math.Float32bits(t24.F1))
	t26 := t23 | int64(uint32(t25))<<32
	t27 := v2
	t28 := int32(math.Float32bits(t27.F2))
	t29 := int64(uint32(t28))
	t30 := v2
	t31 := int32(math.Float32bits(t30.F3))
	return t26 + i64_rotl(t29|int64(uint32(t31))<<32, int64(17))
}
func (m *Module) Xop152(v0, v1 int64) int64 {
	var v2 vec128f64
	var v3 vec128f32
	var _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := math.Float32frombits(uint32(int32(v1)))
	t9 := vec128f32{(t8), (t8), (t8), (t8)}
	t10 := math.Float32frombits(uint32(int32(v0)))
	t11 := vec128f32{t9.F0, (t10), t9.F2, t9.F3}
	t12 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t13 := vec128f32{t11.F0, t11.F1, (t12), t11.F3}
	t14 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t15 := vec128f32{t13.F0, t13.F1, t13.F2, (t14)}
	t16 := vec128f32{float32(t7.F0 + t15.F0), float32(t7.F1 + t15.F1), float32(t7.F2 + t15.F2), float32(t7.F3 + t15.F3)}
	v3 = t16
	t17 := v3
	t18 := vec128f64{float64(t17.F0), float64(t17.F1)}
	t19 := vec128f64{math.Float64frombits(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t18.D0))))) ^ (1 << 63)), math.Float64frombits(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t18.D1))))) ^ (1 << 63))}
	v2 = t19
	t20 := v2
	t21 := int64((uint64(uint32(math.Float64bits(t20.D0))) | uint64(uint32((math.Float64bits(t20.D0))>>32))<<32))
	t22 := v2
	t23 := int64((uint64(uint32(math.Float64bits(t22.D1))) | uint64(uint32((math.Float64bits(t22.D1))>>32))<<32))
	return t21 + i64_rotl(t23, int64(17))
}
func (m *Module) Xop153(v0, v1 int64) int64 {
	var v2, v3 vec128f64
	var _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 + t7.D0), float64(t3.D1 + t7.D1)}
	v3 = t8
	t9 := v3
	t10 := vec128f64{math.Float64frombits(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))) ^ (1 << 63)), math.Float64frombits(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))) ^ (1 << 63))}
	v2 = t10
	t11 := v2
	t12 := int64((uint64(uint32(math.Float64bits(t11.D0))) | uint64(uint32((math.Float64bits(t11.D0))>>32))<<32))
	t13 := v2
	t14 := int64((uint64(uint32(math.Float64bits(t13.D1))) | uint64(uint32((math.Float64bits(t13.D1))>>32))<<32))
	return t12 + i64_rotl(t14, int64(17))
}
func (m *Module) Xop154(v0, v1 int64) int64 {
	var q16 *[16]byte
	mem := m.memory
	var _, _ vec128
	var v3 vec128f64
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 + t7.D0), float64(t3.D1 + t7.D1)}
	v3 = t8
	t9 := v3
	q16 = (*[16]byte)(mem[uint64(uint32(int32(48))) : uint64(uint32(int32(48)))+16])
	q16[0] = byte(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))))
	q16[1] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 8))
	q16[2] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 16))
	q16[3] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 24))
	q16[4] = byte(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 32))
	q16[5] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32) >> 8))
	q16[6] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32) >> 16))
	q16[7] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32) >> 24))
	q16[8] = byte(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))))
	q16[9] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 8))
	q16[10] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 16))
	q16[11] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 24))
	q16[12] = byte(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 32))
	q16[13] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32) >> 8))
	q16[14] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32) >> 16))
	q16[15] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32) >> 24))
	t10 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(48))) : uint64(uint32(i32(48)))+8])[:]))
	t11 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(56))) : uint64(uint32(i32(56)))+8])[:]))
	return t10 + i64_rotl(t11, int64(17))
}
func (m *Module) Xop155(v0, v1 int64) int64 {
	var v2 vec128f32
	var v3 vec128f64
	var _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 + t7.D0), float64(t3.D1 + t7.D1)}
	v3 = t8
	t9 := v3
	t10 := vec128f32{math.Float32frombits(math.Float32bits(math.Float32frombits(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits(math.Float32frombits(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32))) ^ (1 << 31)), math.Float32frombits(math.Float32bits(math.Float32frombits(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))))) ^ (1 << 31)), math.Float32frombits(math.Float32bits(math.Float32frombits(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32))) ^ (1 << 31))}
	v2 = t10
	t11 := v2
	t12 := int32(math.Float32bits(t11.F0))
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(math.Float32bits(t14.F1))
	t16 := t13 | int64(uint32(t15))<<32
	t17 := v2
	t18 := int32(math.Float32bits(t17.F2))
	t19 := int64(uint32(t18))
	t20 := v2
	t21 := int32(math.Float32bits(t20.F3))
	return t16 + i64_rotl(t19|int64(uint32(t21))<<32, int64(17))
}
