// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"encoding/binary"
	"math"
	"math/bits"
)

type Module struct {
	memory     []byte
	memBacking []byte
	maxMem     int64
	g0         float64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memBacking = make([]byte, 65536)
	m.memory = m.memBacking
	m.g0 = math.Float64frombits(0x0)
	return m
}

// MemoryMax is the most bytes the module's memory can grow to
// through its own memory.grow: its declared maximum.
func (m *Module) MemoryMax() int64 { return 4294967296 }

// UseMemory moves the module's memory to the start of buf's backing array,
// where it keeps its size and contents and grows in place, without
// copying or allocating, as far as buf's capacity allows (past it, it moves
// to a new array in the Go heap). buf's bytes past the memory's size must
// be zero, and nothing else may write to them. UseMemory returns false,
// and leaves the memory where it is, when buf's capacity is less than the
// memory's size (a nil buf included). Slices of the memory taken before
// the call are stale after it, as after the memory grows.
func (m *Module) UseMemory(buf []byte) bool {
	n := len(m.memory)
	if cap(buf) < n {
		return false
	}
	buf = buf[:cap(buf)]
	copy(buf, m.memory)
	m.memBacking = buf
	m.memory = buf[:n:n]
	return true
}
func (m *Module) Xop0(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.RoundToEven(math.Float64frombits(uint64(v0))))))
}
func (m *Module) Xop1(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.Floor(math.Float64frombits(uint64(v0))))))
}
func (m *Module) Xop2(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.Ceil(math.Float64frombits(uint64(v0))))))
}
func (m *Module) Xop3(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.Trunc(math.Float64frombits(uint64(v0))))))
}
func (m *Module) Xop4(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.Sqrt(math.Float64frombits(uint64(v0))))))
}
func (m *Module) Xop5(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_abs(math.Float64frombits(uint64(v0)))))
}
func (m *Module) Xop6(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_neg(math.Float64frombits(uint64(v0)))))
}
func (m *Module) Xop7(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.RoundToEven(float64(math.Float32frombits(uint32(int32(v0)))))))))))
}
func (m *Module) Xop8(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Floor(float64(math.Float32frombits(uint32(int32(v0)))))))))))
}
func (m *Module) Xop9(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Ceil(float64(math.Float32frombits(uint32(int32(v0)))))))))))
}
func (m *Module) Xop10(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Trunc(float64(math.Float32frombits(uint32(int32(v0)))))))))))
}
func (m *Module) Xop11(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Sqrt(float64(math.Float32frombits(uint32(int32(v0)))))))))))
}
func (m *Module) Xop12(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_abs(math.Float32frombits(uint32(int32(v0))))))))
}
func (m *Module) Xop13(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_neg(math.Float32frombits(uint32(int32(v0))))))))
}
func (m *Module) Xop14(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float64frombits(uint64(v0))))))))
}
func (m *Module) Xop15(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float32frombits(uint32(int32(v0)))))))
}
func (m *Module) Xop16(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))))
}
func (m *Module) Xop17(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float64frombits(uint64(v0)) - math.Float64frombits(uint64(v1))))))
}
func (m *Module) Xop18(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float64frombits(uint64(v0)) * math.Float64frombits(uint64(v1))))))
}
func (m *Module) Xop19(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float64frombits(uint64(v0)) / math.Float64frombits(uint64(v1))))))
}
func (m *Module) Xop20(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_min(math.Float64frombits(uint64(v0)), math.Float64frombits(uint64(v1)))))
}
func (m *Module) Xop21(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_max(math.Float64frombits(uint64(v0)), math.Float64frombits(uint64(v1)))))
}
func (m *Module) Xop22(v0, v1 int64) int64 {
	return int64(math.Float64bits(math.Copysign(math.Float64frombits(uint64(v0)), math.Float64frombits(uint64(v1)))))
}
func (m *Module) Xop23(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1)))))))))
}
func (m *Module) Xop24(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) - math.Float32frombits(uint32(int32(v1)))))))))
}
func (m *Module) Xop25(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) * math.Float32frombits(uint32(int32(v1)))))))))
}
func (m *Module) Xop26(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) / math.Float32frombits(uint32(int32(v1)))))))))
}
func (m *Module) Xop27(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_min(math.Float32frombits(uint32(int32(v0))), math.Float32frombits(uint32(int32(v1))))))))
}
func (m *Module) Xop28(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_max(math.Float32frombits(uint32(int32(v0))), math.Float32frombits(uint32(int32(v1))))))))
}
func (m *Module) Xop29(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_copysign(math.Float32frombits(uint32(int32(v0))), math.Float32frombits(uint32(int32(v1))))))))
}
func (m *Module) Xop30(v0, v1 int64) int64 {
	t0 := i32_trunc_f32_s(math.Float32frombits(uint32(int32(v0))))
	return int64(uint32(t0))
}
func (m *Module) Xop31(v0, v1 int64) int64 {
	t0 := i32_trunc_f32_u(math.Float32frombits(uint32(int32(v0))))
	return int64(uint32(t0))
}
func (m *Module) Xop32(v0, v1 int64) int64 {
	t0 := i32_trunc_f64_s(math.Float64frombits(uint64(v0)))
	return int64(uint32(t0))
}
func (m *Module) Xop33(v0, v1 int64) int64 {
	t0 := i32_trunc_f64_u(math.Float64frombits(uint64(v0)))
	return int64(uint32(t0))
}
func (m *Module) Xop34(v0, v1 int64) int64 {
	t0 := i64_trunc_f32_s(math.Float32frombits(uint32(int32(v0))))
	return t0
}
func (m *Module) Xop35(v0, v1 int64) int64 {
	t0 := i64_trunc_f32_u(math.Float32frombits(uint32(int32(v0))))
	return t0
}
func (m *Module) Xop36(v0, v1 int64) int64 {
	t0 := i64_trunc_f64_s(math.Float64frombits(uint64(v0)))
	return t0
}
func (m *Module) Xop37(v0, v1 int64) int64 {
	t0 := i64_trunc_f64_u(math.Float64frombits(uint64(v0)))
	return t0
}
func (m *Module) Xop38(v0, v1 int64) int64 {
	return int64(uint32(i32_trunc_sat_f32_s(math.Float32frombits(uint32(int32(v0))))))
}
func (m *Module) Xop39(v0, v1 int64) int64 {
	return int64(uint32(i32_trunc_sat_f32_u(math.Float32frombits(uint32(int32(v0))))))
}
func (m *Module) Xop40(v0, v1 int64) int64 {
	return int64(uint32(i32_trunc_sat_f64_s(math.Float64frombits(uint64(v0)))))
}
func (m *Module) Xop41(v0, v1 int64) int64 {
	return int64(uint32(i32_trunc_sat_f64_u(math.Float64frombits(uint64(v0)))))
}
func (m *Module) Xop42(v0, v1 int64) int64 {
	return i64_trunc_sat_f32_s(math.Float32frombits(uint32(int32(v0))))
}
func (m *Module) Xop43(v0, v1 int64) int64 {
	return i64_trunc_sat_f32_u(math.Float32frombits(uint32(int32(v0))))
}
func (m *Module) Xop44(v0, v1 int64) int64 {
	return i64_trunc_sat_f64_s(math.Float64frombits(uint64(v0)))
}
func (m *Module) Xop45(v0, v1 int64) int64 {
	return i64_trunc_sat_f64_u(math.Float64frombits(uint64(v0)))
}
func (m *Module) Xop46(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(float32(int32(v0))))))
}
func (m *Module) Xop47(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(float32(uint32(int32(v0)))))))
}
func (m *Module) Xop48(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_convert_i64_s(v0)))))
}
func (m *Module) Xop49(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_convert_i64_u(v0)))))
}
func (m *Module) Xop50(v0, v1 int64) int64 {
	return int64(math.Float64bits(float64(int32(v0))))
}
func (m *Module) Xop51(v0, v1 int64) int64 {
	return int64(math.Float64bits(float64(uint32(int32(v0)))))
}
func (m *Module) Xop52(v0, v1 int64) int64 {
	return int64(math.Float64bits(float64(v0)))
}
func (m *Module) Xop53(v0, v1 int64) int64 {
	return int64(math.Float64bits(float64(uint64(v0))))
}
func (m *Module) Xop54(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(float64(math.Float64frombits(uint64(v0))*math.Float64frombits(uint64(v1))) + math.Float64frombits(0xbff0000000000000)))))
}
func (m *Module) Xop55(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(math.Float64frombits(0x3ff0000000000000) - float64(math.Float64frombits(uint64(v0))*math.Float64frombits(uint64(v1)))))))
}
func (m *Module) Xop56(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(f64_neg(f64_canon(float64(math.Float64frombits(uint64(v0))*math.Float64frombits(uint64(v1))))) + math.Float64frombits(0x3ff0000000000000)))))
}
func (m *Module) Xop57(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.Sqrt(float64(math.Float64frombits(uint64(v0)) / math.Float64frombits(uint64(v1)))))))
}
func (m *Module) Xop58(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_min(float64(math.Float64frombits(uint64(v0))+math.Float64frombits(uint64(v1))), math.Float64frombits(0x0))))
}
func (m *Module) Xop59(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_neg(f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1)))))))
}
func (m *Module) Xop60(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_abs(f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1)))))))
}
func (m *Module) Xop61(v0, v1 int64) int64 {
	return int64(math.Float64bits(math.Copysign(f64_canon(float64(math.Float64frombits(uint64(v0))+math.Float64frombits(uint64(v1)))), math.Float64frombits(uint64(v1)))))
}
func (m *Module) Xop62(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(math.Floor(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1)))))))
}
func (m *Module) Xop63(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(float32(math.Float32frombits(uint32(int32(v0)))*math.Float32frombits(uint32(int32(v1)))) + math.Float32frombits(0xbf800000)))))))
}
func (m *Module) Xop64(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float32frombits(0x3f800000) - float32(math.Float32frombits(uint32(int32(v0)))*math.Float32frombits(uint32(int32(v1))))))))))
}
func (m *Module) Xop65(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_neg(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1))))))))))
}
func (m *Module) Xop66(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_abs(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1))))))))))
}
func (m *Module) Xop67(v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(float32(float64(math.Float64frombits(uint64(v0))*math.Float64frombits(uint64(v1)))) + math.Float32frombits(0x0)))))))
}
func (m *Module) Xop68(v0, v1 int64) int64 {
	return int64(math.Float64bits(f64_canon(float64(float64(float32(math.Float32frombits(uint32(int32(v0)))*math.Float32frombits(uint32(int32(v1))))) + math.Float64frombits(0xbff0000000000000)))))
}
func fn69(v0 float64) int64 {
	return int64(math.Float64bits(v0))
}
func fn70(v0, v1 float64) float64 {
	var v2 float64
	v2 = f64_canon(float64(v0 + v1))
	return v2
}
func (m *Module) Xop69(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	return int64(math.Float64bits(f64_neg(v2)))
}
func (m *Module) Xop70(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	return int64(math.Float64bits(f64_abs(v2)))
}
func (m *Module) Xop71(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	return int64(math.Float64bits(math.Copysign(v2, math.Float64frombits(uint64(v1)))))
}
func (m *Module) Xop72(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	return int64(math.Float64bits(v2))
}
func (m *Module) Xop73(v0, v1 int64) int64 {
	mem := m.memory
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	binary.LittleEndian.PutUint64((*[8]byte)(mem[uint64(uint32(i32(8))) : uint64(uint32(i32(8)))+8])[:], math.Float64bits(v2))
	t0 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(8))) : uint64(uint32(i32(8)))+8])[:]))
	return t0
}
func (m *Module) Xop74(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	t0 := fn69(v2)
	return t0
}
func (m *Module) Xop75(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	m.g0 = v2
	t0 := m.g0
	return int64(math.Float64bits(t0))
}
func (m *Module) Xop76(v0, v1 int64) int64 {
	var _, _ float64
	var _, _ float32
	var _ int32
	t0 := fn70(math.Float64frombits(uint64(v0)), math.Float64frombits(uint64(v1)))
	return int64(math.Float64bits(t0))
}
func (m *Module) Xop77(v0, v1 int64) int64 {
	var v2, v3 float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) * math.Float64frombits(uint64(v1))))
	v3 = f64_canon(float64(v2 + math.Float64frombits(0xbff0000000000000)))
	return int64(math.Float64bits(v3))
}
func (m *Module) Xop78(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	var p0 int32
	if v2 < math.Float64frombits(0x0) {
		p0 = 1
	}
	return int64(uint32(p0))
}
func (m *Module) Xop79(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	var p0 int32
	if v2 != v2 {
		p0 = 1
	}
	return int64(uint32(p0))
}
func (m *Module) Xop80(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	return int64(math.Float64bits(f64_min(v2, math.Float64frombits(0x0))))
}
func (m *Module) Xop81(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	return i64_trunc_sat_f64_s(v2)
}
func (m *Module) Xop82(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(math.Sqrt(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1)))))
	return int64(math.Float64bits(f64_neg(v2)))
}
func (m *Module) Xop83(v0, v1 int64) int64 {
	var v2, v3 float64
	var _, _ float32
	var _ int32
	v2 = f64_canon(float64(math.Float64frombits(uint64(v0)) + math.Float64frombits(uint64(v1))))
	p0 := math.Float64frombits(uint64(v0))
	if v1 < int64(0) {
		p0 = v2
	}
	v3 = p0
	return int64(math.Float64bits(f64_neg(v3)))
}
func (m *Module) Xop84(v0, v1 int64) int64 {
	var v2, _ float64
	var _, _ float32
	var v6 int32
	v2 = math.Float64frombits(uint64(v0))
	v6 = int32(3)
l0:
	v2 = f64_canon(float64(v2 + math.Float64frombits(uint64(v1))))
	v6 = v6 - int32(1)
	if v6 != 0 {
		goto l0
	}
	return int64(math.Float64bits(f64_neg(v2)))
}
func (m *Module) Xop85(v0, v1 int64) int64 {
	var _, _ float64
	var v4, _ float32
	var _ int32
	v4 = f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1)))))
	return int64(uint32(int32(math.Float32bits(f32_neg(v4)))))
}
func (m *Module) Xop86(v0, v1 int64) int64 {
	var _, _ float64
	var v4, _ float32
	var _ int32
	v4 = f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1)))))
	return int64(uint32(int32(math.Float32bits(f32_copysign(v4, math.Float32frombits(uint32(int32(v1))))))))
}
func (m *Module) Xop87(v0, v1 int64) int64 {
	mem := m.memory
	var _, _ float64
	var v4, _ float32
	var _ int32
	v4 = f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1)))))
	binary.LittleEndian.PutUint32((*[4]byte)(mem[uint64(uint32(i32(16))) : uint64(uint32(i32(16)))+4])[:], math.Float32bits(v4))
	t0 := int64(binary.LittleEndian.Uint32((*[4]byte)(mem[uint64(uint32(i32(16))) : uint64(uint32(i32(16)))+4])[:]))
	return t0
}
func (m *Module) Xop88(v0, v1 int64) int64 {
	var _, _ float64
	var v4, _ float32
	var _ int32
	v4 = f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1)))))
	return int64(uint32(int32(math.Float32bits(v4))))
}
func (m *Module) Xop89(v0, v1 int64) int64 {
	var _, _ float64
	var v4, _ float32
	var _ int32
	v4 = f32_canon(float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1)))))
	return int64(math.Float64bits(f64_neg(f64_canon(float64(v4)))))
}
func (m *Module) Xop90(v0, v1 int64) int64 {
	var _, _ float64
	var v4, v5 float32
	var _ int32
	v4 = f32_canon(float32(math.Float32frombits(uint32(int32(v0))) * math.Float32frombits(uint32(int32(v1)))))
	v5 = f32_canon(float32(v4 + math.Float32frombits(0xbf800000)))
	return int64(uint32(int32(math.Float32bits(f32_neg(v5)))))
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func f32_abs(x float32) float32 {
	return math.Float32frombits(math.Float32bits(x) &^ (1 << 31))
}

//go:nosplit
func f64_abs(x float64) float64 {
	return math.Float64frombits(math.Float64bits(x) &^ (1 << 63))
}

//go:nosplit
func f32_neg(x float32) float32 {
	return math.Float32frombits(math.Float32bits(x) ^ 1<<31)
}

//go:nosplit
func f64_neg(x float64) float64 {
	return math.Float64frombits(math.Float64bits(x) ^ 1<<63)
}

//go:nosplit
func f32_copysign(x, y float32) float32 {
	return math.Float32frombits(math.Float32bits(x)&^(1<<31) | math.Float32bits(y)&(1<<31))
}

//go:nosplit
func f32_canon(x float32) float32 {
	if x != x {
		return math.Float32frombits(0x7fc00000)
	}
	return x
}

//go:nosplit
func f64_canon(x float64) float64 {
	if x != x {
		return math.Float64frombits(0x7ff8000000000000)
	}
	return x
}

//go:nosplit
func f32_min(x, y float32) float32 {
	if m := min(x, y); m == m {
		return m
	}
	return math.Float32frombits(0x7fc00000)
}

//go:nosplit
func f32_max(x, y float32) float32 {
	if m := max(x, y); m == m {
		return m
	}
	return math.Float32frombits(0x7fc00000)
}

//go:nosplit
func f64_min(x, y float64) float64 {
	if m := min(x, y); m == m {
		return m
	}
	return math.Float64frombits(0x7ff8000000000000)
}

//go:nosplit
func f64_max(x, y float64) float64 {
	if m := max(x, y); m == m {
		return m
	}
	return math.Float64frombits(0x7ff8000000000000)
}

//go:nosplit
func f32_convert_i64_u(x int64) float32 {
	u := uint64(x)
	if u < 1<<53 {
		return float32(float64(int64(u)))
	}
	s := uint(bits.Len64(u) - 53)
	y := u >> s
	if u&(1<<s-1) != 0 {
		y |= 1
	}
	return float32(float64(int64(y)) * math.Float64frombits(uint64(1023+s)<<52))
}

//go:nosplit
func f32_convert_i64_s(x int64) float32 {
	if x < 0 {

		return -f32_convert_i64_u(-x)
	}
	return f32_convert_i64_u(x)
}

// Returns the truncation of f toward zero as a 64-bit two's complement
// integer, for every f whose magnitude is below 2^64 (the caller has
// checked it). The significand, its implicit one restored, is aligned to
// the top of a uint64, where it stands for the magnitude scaled into
// [2^63, 2^64), and shifted right by 63 less the exponent; a magnitude below
// one (zero and the subnormals included) shifts by 64 or more, which Go
// defines to yield zero. It is how strictgo's reproducible.Trunc computes.
//
//go:nosplit
func trunc_u64(f float64) uint64 {
	b := math.Float64bits(f)
	u := (b<<11 | 1<<63) >> (1086 - b>>52&0x7ff)
	sign := uint64(int64(b) >> 63)
	return u ^ sign - sign
}

// Returns x, an integer of magnitude below 2^51 (the caller has checked
// it), as an int64. Adding 1.5 * 2^52 is exact for such an x, and leaves it
// in the significand's low bits, offset by the constant's own bits: two
// instructions beside the addition, fewer than a shift by the exponent.
//
//go:nosplit
func trunc_small(x float64) int64 {
	return int64(math.Float64bits(x+0x1.8p52)) - 0x4338000000000000
}

//go:nosplit
func i32_trunc_f64_s(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	}
	return int32(trunc_small(x))
}

//go:nosplit
func i32_trunc_f32_s(f float32) int32 {
	x := math.Trunc(float64(f))
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt32 || x > math.MaxInt32:
		panic("integer overflow")
	}
	return int32(trunc_small(x))
}

//go:nosplit
func i32_trunc_f64_u(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	}
	return int32(trunc_small(x))
}

//go:nosplit
func i32_trunc_f32_u(f float32) int32 {
	x := math.Trunc(float64(f))
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	}
	return int32(trunc_small(x))
}

//go:nosplit
func i64_trunc_f64_s(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	}
	return int64(trunc_u64(f))
}

//go:nosplit
func i64_trunc_f32_s(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < math.MinInt64 || x >= math.MaxInt64:
		panic("integer overflow")
	}
	return int64(trunc_u64(float64(f)))
}

//go:nosplit
func i64_trunc_f64_u(f float64) int64 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < 0 || x >= math.MaxUint64:
		panic("integer overflow")
	}
	return int64(trunc_u64(f))
}

//go:nosplit
func i64_trunc_f32_u(f float32) int64 {
	x := math.Trunc(float64(f))
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < 0 || x >= math.MaxUint64:
		panic("integer overflow")
	}
	return int64(trunc_u64(float64(f)))
}

//go:nosplit
func i32_trunc_sat_f64_s(f float64) int32 {
	switch {
	case f <= math.MinInt32:
		return math.MinInt32
	case f >= math.MaxInt32:
		return math.MaxInt32
	case f != f:
		return 0
	}
	return int32(trunc_small(math.Trunc(f)))
}

//go:nosplit
func i32_trunc_sat_f32_s(f float32) int32 {
	switch {
	case f <= math.MinInt32:
		return math.MinInt32
	case f >= math.MaxInt32:
		return math.MaxInt32
	case f != f:
		return 0
	}
	return int32(trunc_small(math.Trunc(float64(f))))
}

//go:nosplit
func i32_trunc_sat_f64_u(f float64) int32 {
	switch {
	case f <= 0 || f != f:
		return 0
	case f >= math.MaxUint32:
		return -1
	}
	return int32(trunc_small(math.Trunc(f)))
}

//go:nosplit
func i32_trunc_sat_f32_u(f float32) int32 {
	switch {
	case f <= 0 || f != f:
		return 0
	case f >= math.MaxUint32:
		return -1
	}
	return int32(trunc_small(math.Trunc(float64(f))))
}

//go:nosplit
func i64_trunc_sat_f64_s(f float64) int64 {
	switch {
	case f < math.MinInt64:
		return math.MinInt64
	case f >= math.MaxInt64:
		return math.MaxInt64
	case f != f:
		return 0
	}
	return int64(trunc_u64(f))
}

//go:nosplit
func i64_trunc_sat_f32_s(f float32) int64 {
	switch {
	case f < math.MinInt64:
		return math.MinInt64
	case f >= math.MaxInt64:
		return math.MaxInt64
	case f != f:
		return 0
	}
	return int64(trunc_u64(float64(f)))
}

//go:nosplit
func i64_trunc_sat_f64_u(f float64) int64 {
	switch {
	case f <= 0 || f != f:
		return 0
	case f >= math.MaxUint64:
		return -1
	}
	return int64(trunc_u64(f))
}

//go:nosplit
func i64_trunc_sat_f32_u(f float32) int64 {
	switch {
	case f <= 0 || f != f:
		return 0
	case f >= math.MaxUint64:
		return -1
	}
	return int64(trunc_u64(float64(f)))
}

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	return binary.LittleEndian.Uint32(mem[addr:])
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	binary.LittleEndian.PutUint32(mem[addr:], val)
}

//go:nosplit
func load64[T uint32 | uint64](mem []byte, addr T) uint64 {
	return binary.LittleEndian.Uint64(mem[addr:])
}

//go:nosplit
func store64[T uint32 | uint64](mem []byte, addr T, val uint64) {
	binary.LittleEndian.PutUint64(mem[addr:], val)
}

// Grows the memory *mem by delta pages, up to max, and returns its old size
// in pages, or -1. *back is the memory's backing array: *mem is its prefix,
// with its capacity cut to its length, so no slice of the memory reaches
// past its end, and back's bytes past the memory's end are zero. Growth
// within back is in place: no copy, no allocation. Past it, the memory moves
// to a new backing array of twice the size, at least what the growth needs,
// at most max pages.
func memory_grow(mem, back *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	size := int(new << 16)
	if size > cap(*back) {
		n := int(min(uint64(cap(*back))>>15, uint64(max)) << 16)
		if n < size {
			n = size
		}
		b := make([]byte, n)
		copy(b, buf)
		*back = b
	}
	*mem = (*back)[:size:size]
	return int64(old)
}
