// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package wasm2go

import (
	"encoding/binary"
	"math"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func (m *Module) Xop91(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v2 = t8
	t9 := v2
	t10 := int32((uint32(lane_canon32(t9.L0))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32((uint32(lane_canon32(t12.L1))))
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop92(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) - math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) - math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) - math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) - math.Float32frombits(t7.L3))))}
	v2 = t8
	t9 := v2
	t10 := int32((uint32(lane_canon32(t9.L0))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32((uint32(lane_canon32(t12.L1))))
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop93(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) * math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) * math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) * math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) * math.Float32frombits(t7.L3))))}
	v2 = t8
	t9 := v2
	t10 := int32((uint32(lane_canon32(t9.L0))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32((uint32(lane_canon32(t12.L1))))
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop94(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) / math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) / math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) / math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) / math.Float32frombits(t7.L3))))}
	v2 = t8
	t9 := v2
	t10 := int32((uint32(lane_canon32(t9.L0))))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32((uint32(lane_canon32(t12.L1))))
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop95(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L0), math.Float32frombits(t7.L0))))), uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L1), math.Float32frombits(t7.L1))))), uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L2), math.Float32frombits(t7.L2))))), uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L3), math.Float32frombits(t7.L3)))))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop96(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_canon32(math.Float32bits(max(math.Float32frombits(t3.L0), math.Float32frombits(t7.L0))))), uint32(lane_canon32(math.Float32bits(max(math.Float32frombits(t3.L1), math.Float32frombits(t7.L1))))), uint32(lane_canon32(math.Float32bits(max(math.Float32frombits(t3.L2), math.Float32frombits(t7.L2))))), uint32(lane_canon32(math.Float32bits(max(math.Float32frombits(t3.L3), math.Float32frombits(t7.L3)))))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop97(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_pmin32(t3.L0, t7.L0)), uint32(lane_pmin32(t3.L1, t7.L1)), uint32(lane_pmin32(t3.L2, t7.L2)), uint32(lane_pmin32(t3.L3, t7.L3))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop98(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_pmax32(t3.L0, t7.L0)), uint32(lane_pmax32(t3.L1, t7.L1)), uint32(lane_pmax32(t3.L2, t7.L2)), uint32(lane_pmax32(t3.L3, t7.L3))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop99(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_mask32(math.Float32frombits(t3.L0) == math.Float32frombits(t7.L0))), uint32(lane_mask32(math.Float32frombits(t3.L1) == math.Float32frombits(t7.L1))), uint32(lane_mask32(math.Float32frombits(t3.L2) == math.Float32frombits(t7.L2))), uint32(lane_mask32(math.Float32frombits(t3.L3) == math.Float32frombits(t7.L3)))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop100(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_mask32(math.Float32frombits(t3.L0) != math.Float32frombits(t7.L0))), uint32(lane_mask32(math.Float32frombits(t3.L1) != math.Float32frombits(t7.L1))), uint32(lane_mask32(math.Float32frombits(t3.L2) != math.Float32frombits(t7.L2))), uint32(lane_mask32(math.Float32frombits(t3.L3) != math.Float32frombits(t7.L3)))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop101(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_mask32(math.Float32frombits(t3.L0) < math.Float32frombits(t7.L0))), uint32(lane_mask32(math.Float32frombits(t3.L1) < math.Float32frombits(t7.L1))), uint32(lane_mask32(math.Float32frombits(t3.L2) < math.Float32frombits(t7.L2))), uint32(lane_mask32(math.Float32frombits(t3.L3) < math.Float32frombits(t7.L3)))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop102(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_mask32(math.Float32frombits(t3.L0) > math.Float32frombits(t7.L0))), uint32(lane_mask32(math.Float32frombits(t3.L1) > math.Float32frombits(t7.L1))), uint32(lane_mask32(math.Float32frombits(t3.L2) > math.Float32frombits(t7.L2))), uint32(lane_mask32(math.Float32frombits(t3.L3) > math.Float32frombits(t7.L3)))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop103(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_mask32(math.Float32frombits(t3.L0) <= math.Float32frombits(t7.L0))), uint32(lane_mask32(math.Float32frombits(t3.L1) <= math.Float32frombits(t7.L1))), uint32(lane_mask32(math.Float32frombits(t3.L2) <= math.Float32frombits(t7.L2))), uint32(lane_mask32(math.Float32frombits(t3.L3) <= math.Float32frombits(t7.L3)))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop104(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_mask32(math.Float32frombits(t3.L0) >= math.Float32frombits(t7.L0))), uint32(lane_mask32(math.Float32frombits(t3.L1) >= math.Float32frombits(t7.L1))), uint32(lane_mask32(math.Float32frombits(t3.L2) >= math.Float32frombits(t7.L2))), uint32(lane_mask32(math.Float32frombits(t3.L3) >= math.Float32frombits(t7.L3)))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}
func (m *Module) Xop105(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(math.Sqrt(float64(math.Float32frombits(t3.L0)))))), uint32(math.Float32bits(float32(math.Sqrt(float64(math.Float32frombits(t3.L1)))))), uint32(math.Float32bits(float32(math.Sqrt(float64(math.Float32frombits(t3.L2)))))), uint32(math.Float32bits(float32(math.Sqrt(float64(math.Float32frombits(t3.L3))))))}
	v2 = t4
	t5 := v2
	t6 := int32((uint32(lane_canon32(t5.L0))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32((uint32(lane_canon32(t8.L1))))
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop106(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(math.Ceil(float64(math.Float32frombits(t3.L0)))))), uint32(math.Float32bits(float32(math.Ceil(float64(math.Float32frombits(t3.L1)))))), uint32(math.Float32bits(float32(math.Ceil(float64(math.Float32frombits(t3.L2)))))), uint32(math.Float32bits(float32(math.Ceil(float64(math.Float32frombits(t3.L3))))))}
	v2 = t4
	t5 := v2
	t6 := int32((uint32(lane_canon32(t5.L0))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32((uint32(lane_canon32(t8.L1))))
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop107(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(math.Floor(float64(math.Float32frombits(t3.L0)))))), uint32(math.Float32bits(float32(math.Floor(float64(math.Float32frombits(t3.L1)))))), uint32(math.Float32bits(float32(math.Floor(float64(math.Float32frombits(t3.L2)))))), uint32(math.Float32bits(float32(math.Floor(float64(math.Float32frombits(t3.L3))))))}
	v2 = t4
	t5 := v2
	t6 := int32((uint32(lane_canon32(t5.L0))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32((uint32(lane_canon32(t8.L1))))
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop108(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(math.Trunc(float64(math.Float32frombits(t3.L0)))))), uint32(math.Float32bits(float32(math.Trunc(float64(math.Float32frombits(t3.L1)))))), uint32(math.Float32bits(float32(math.Trunc(float64(math.Float32frombits(t3.L2)))))), uint32(math.Float32bits(float32(math.Trunc(float64(math.Float32frombits(t3.L3))))))}
	v2 = t4
	t5 := v2
	t6 := int32((uint32(lane_canon32(t5.L0))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32((uint32(lane_canon32(t8.L1))))
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop109(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(math.RoundToEven(float64(math.Float32frombits(t3.L0)))))), uint32(math.Float32bits(float32(math.RoundToEven(float64(math.Float32frombits(t3.L1)))))), uint32(math.Float32bits(float32(math.RoundToEven(float64(math.Float32frombits(t3.L2)))))), uint32(math.Float32bits(float32(math.RoundToEven(float64(math.Float32frombits(t3.L3))))))}
	v2 = t4
	t5 := v2
	t6 := int32((uint32(lane_canon32(t5.L0))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32((uint32(lane_canon32(t8.L1))))
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop110(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(t3.L0 &^ (1 << 31)), uint32(t3.L1 &^ (1 << 31)), uint32(t3.L2 &^ (1 << 31)), uint32(t3.L3 &^ (1 << 31))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop111(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(t3.L0 ^ (1 << 31)), uint32(t3.L1 ^ (1 << 31)), uint32(t3.L2 ^ (1 << 31)), uint32(t3.L3 ^ (1 << 31))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop112(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32))
	t11 := v2
	t12 := int64((uint64((uint32(uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32))))>>32)))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop113(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) - math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) - math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) - math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) - math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32))
	t11 := v2
	t12 := int64((uint64((uint32(uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32))))>>32)))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop114(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) * math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) * math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) * math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) * math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32))
	t11 := v2
	t12 := int64((uint64((uint32(uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32))))>>32)))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop115(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) / math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) / math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) / math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) / math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32))
	t11 := v2
	t12 := int64((uint64((uint32(uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32))))>>32)))<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop116(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_canon64(math.Float64bits(min(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)), math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))))), uint32((uint64(lane_canon64(math.Float64bits(min(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)), math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))))) >> 32), uint32(uint64(lane_canon64(math.Float64bits(min(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)), math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))))), uint32((uint64(lane_canon64(math.Float64bits(min(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)), math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop117(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_canon64(math.Float64bits(max(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)), math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))))), uint32((uint64(lane_canon64(math.Float64bits(max(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)), math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))))) >> 32), uint32(uint64(lane_canon64(math.Float64bits(max(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)), math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))))), uint32((uint64(lane_canon64(math.Float64bits(max(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)), math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop118(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_pmin64((uint64(t3.L0) | uint64(t3.L1)<<32), (uint64(t7.L0) | uint64(t7.L1)<<32)))), uint32((uint64(lane_pmin64((uint64(t3.L0) | uint64(t3.L1)<<32), (uint64(t7.L0) | uint64(t7.L1)<<32)))) >> 32), uint32(uint64(lane_pmin64((uint64(t3.L2) | uint64(t3.L3)<<32), (uint64(t7.L2) | uint64(t7.L3)<<32)))), uint32((uint64(lane_pmin64((uint64(t3.L2) | uint64(t3.L3)<<32), (uint64(t7.L2) | uint64(t7.L3)<<32)))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop119(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_pmax64((uint64(t3.L0) | uint64(t3.L1)<<32), (uint64(t7.L0) | uint64(t7.L1)<<32)))), uint32((uint64(lane_pmax64((uint64(t3.L0) | uint64(t3.L1)<<32), (uint64(t7.L0) | uint64(t7.L1)<<32)))) >> 32), uint32(uint64(lane_pmax64((uint64(t3.L2) | uint64(t3.L3)<<32), (uint64(t7.L2) | uint64(t7.L3)<<32)))), uint32((uint64(lane_pmax64((uint64(t3.L2) | uint64(t3.L3)<<32), (uint64(t7.L2) | uint64(t7.L3)<<32)))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop120(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) == math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) == math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))) >> 32), uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) == math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) == math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop121(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) != math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) != math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))) >> 32), uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) != math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) != math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop122(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) < math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) < math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))) >> 32), uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) < math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) < math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop123(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) > math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) > math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))) >> 32), uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) > math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) > math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop124(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) <= math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) <= math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))) >> 32), uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) <= math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) <= math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop125(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) >= math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) >= math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32))))) >> 32), uint32(uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) >= math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))), uint32((uint64(lane_mask64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) >= math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64(t9.L0) | uint64(t9.L1)<<32))
	t11 := v2
	t12 := int64((uint64(t11.L2) | uint64(t11.L3)<<32))
	return t10 + i64_rotl(t12, int64(17))
}
func (m *Module) Xop126(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64(math.Float64bits(math.Sqrt(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))), uint32((uint64(math.Float64bits(math.Sqrt(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(math.Sqrt(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))), uint32((uint64(math.Float64bits(math.Sqrt(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64((uint32(uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32))))>>32)))<<32))
	t7 := v2
	t8 := int64((uint64((uint32(uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32))))>>32)))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop127(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64(math.Float64bits(math.Ceil(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))), uint32((uint64(math.Float64bits(math.Ceil(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(math.Ceil(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))), uint32((uint64(math.Float64bits(math.Ceil(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64((uint32(uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32))))>>32)))<<32))
	t7 := v2
	t8 := int64((uint64((uint32(uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32))))>>32)))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop128(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64(math.Float64bits(math.Floor(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))), uint32((uint64(math.Float64bits(math.Floor(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(math.Floor(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))), uint32((uint64(math.Float64bits(math.Floor(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64((uint32(uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32))))>>32)))<<32))
	t7 := v2
	t8 := int64((uint64((uint32(uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32))))>>32)))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop129(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64(math.Float64bits(math.Trunc(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))), uint32((uint64(math.Float64bits(math.Trunc(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(math.Trunc(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))), uint32((uint64(math.Float64bits(math.Trunc(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64((uint32(uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32))))>>32)))<<32))
	t7 := v2
	t8 := int64((uint64((uint32(uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32))))>>32)))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop130(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64(math.Float64bits(math.RoundToEven(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))), uint32((uint64(math.Float64bits(math.RoundToEven(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(math.RoundToEven(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))), uint32((uint64(math.Float64bits(math.RoundToEven(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64((uint32(uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32))))>>32)))<<32))
	t7 := v2
	t8 := int64((uint64((uint32(uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32))))>>32)))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop131(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64((uint64(t3.L0) | uint64(t3.L1)<<32) &^ (1 << 63))), uint32((uint64((uint64(t3.L0) | uint64(t3.L1)<<32) &^ (1 << 63))) >> 32), uint32(uint64((uint64(t3.L2) | uint64(t3.L3)<<32) &^ (1 << 63))), uint32((uint64((uint64(t3.L2) | uint64(t3.L3)<<32) &^ (1 << 63))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(t5.L0) | uint64(t5.L1)<<32))
	t7 := v2
	t8 := int64((uint64(t7.L2) | uint64(t7.L3)<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop132(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(uint64((uint64(t3.L0) | uint64(t3.L1)<<32) ^ (1 << 63))), uint32((uint64((uint64(t3.L0) | uint64(t3.L1)<<32) ^ (1 << 63))) >> 32), uint32(uint64((uint64(t3.L2) | uint64(t3.L3)<<32) ^ (1 << 63))), uint32((uint64((uint64(t3.L2) | uint64(t3.L3)<<32) ^ (1 << 63))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(t5.L0) | uint64(t5.L1)<<32))
	t7 := v2
	t8 := int64((uint64(t7.L2) | uint64(t7.L3)<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop133(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{math.Float32bits(float32(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))), math.Float32bits(float32(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32((uint32(lane_canon32(t5.L0))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32((uint32(lane_canon32(t8.L1))))
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop134(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float64bits(float64(math.Float32frombits(t3.L0)))), uint32((math.Float64bits(float64(math.Float32frombits(t3.L0)))) >> 32), uint32(math.Float64bits(float64(math.Float32frombits(t3.L1)))), uint32((math.Float64bits(float64(math.Float32frombits(t3.L1)))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64((uint32(uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t5.L0) | uint64(t5.L1)<<32))))>>32)))<<32))
	t7 := v2
	t8 := int64((uint64((uint32(uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t7.L2) | uint64(t7.L3)<<32))))>>32)))<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop135(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(int32(t3.L0)))), uint32(math.Float32bits(float32(int32(t3.L1)))), uint32(math.Float32bits(float32(int32(t3.L2)))), uint32(math.Float32bits(float32(int32(t3.L3))))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop136(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float32bits(float32(t3.L0))), uint32(math.Float32bits(float32(t3.L1))), uint32(math.Float32bits(float32(t3.L2))), uint32(math.Float32bits(float32(t3.L3)))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop137(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float64bits(float64(int32(t3.L0)))), uint32((math.Float64bits(float64(int32(t3.L0)))) >> 32), uint32(math.Float64bits(float64(int32(t3.L1)))), uint32((math.Float64bits(float64(int32(t3.L1)))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(t5.L0) | uint64(t5.L1)<<32))
	t7 := v2
	t8 := int64((uint64(t7.L2) | uint64(t7.L3)<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop138(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := int32(v0)
	t1 := vec128{uint32((t0)), uint32((t0)), uint32((t0)), uint32((t0))}
	t2 := int32(v1)
	t3 := vec128{t1.L0, uint32((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(math.Float64bits(float64(t3.L0))), uint32((math.Float64bits(float64(t3.L0))) >> 32), uint32(math.Float64bits(float64(t3.L1))), uint32((math.Float64bits(float64(t3.L1))) >> 32)}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(t5.L0) | uint64(t5.L1)<<32))
	t7 := v2
	t8 := int64((uint64(t7.L2) | uint64(t7.L3)<<32))
	return t6 + i64_rotl(t8, int64(17))
}
func (m *Module) Xop139(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.L0))), uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.L1))), uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.L2))), uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.L3)))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop140(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := vec128{uint32(i32_trunc_sat_f32_u(math.Float32frombits(t3.L0))), uint32(i32_trunc_sat_f32_u(math.Float32frombits(t3.L1))), uint32(i32_trunc_sat_f32_u(math.Float32frombits(t3.L2))), uint32(i32_trunc_sat_f32_u(math.Float32frombits(t3.L3)))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop141(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(i32_trunc_sat_f64_s(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))), uint32(i32_trunc_sat_f64_s(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop142(v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := vec128{uint32(i32_trunc_sat_f64_u(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)))), uint32(i32_trunc_sat_f64_u(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)))), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}
func (m *Module) Xop143(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := vec128{uint32((uint32(lane_canon32(t9.L0))) ^ (1 << 31)), uint32((uint32(lane_canon32(t9.L1))) ^ (1 << 31)), uint32((uint32(lane_canon32(t9.L2))) ^ (1 << 31)), uint32((uint32(lane_canon32(t9.L3))) ^ (1 << 31))}
	v2 = t10
	t11 := v2
	t12 := int32(t11.L0)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L1)
	return t13 | int64(uint32(t15))<<32
}
func (m *Module) Xop144(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := vec128{uint32((uint32(lane_canon32(t9.L0))) &^ (1 << 31)), uint32((uint32(lane_canon32(t9.L1))) &^ (1 << 31)), uint32((uint32(lane_canon32(t9.L2))) &^ (1 << 31)), uint32((uint32(lane_canon32(t9.L3))) &^ (1 << 31))}
	v2 = t10
	t11 := v2
	t12 := int32(t11.L0)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L1)
	return t13 | int64(uint32(t15))<<32
}
func (m *Module) Xop145(v0, v1 int64) int64 {
	var _, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := math.Float32frombits((uint32(lane_canon32(t9.L1))))
	return int64(uint32(int32(math.Float32bits(t10))))
}
func (m *Module) Xop146(v0, v1 int64) int64 {
	var q16 *[16]byte
	mem := m.memory
	var _, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	q16 = (*[16]byte)(mem[uint64(uint32(int32(32))) : uint64(uint32(int32(32)))+16])
	q16[0] = byte((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L0)
	q16[1] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L0 >> 8))
	q16[2] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L0 >> 16))
	q16[3] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L0 >> 24))
	q16[4] = byte((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L1)
	q16[5] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L1 >> 8))
	q16[6] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L1 >> 16))
	q16[7] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L1 >> 24))
	q16[8] = byte((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L2)
	q16[9] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L2 >> 8))
	q16[10] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L2 >> 16))
	q16[11] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L2 >> 24))
	q16[12] = byte((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L3)
	q16[13] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L3 >> 8))
	q16[14] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L3 >> 16))
	q16[15] = byte(((vec128{uint32(lane_canon32(t9.L0)), uint32(lane_canon32(t9.L1)), uint32(lane_canon32(t9.L2)), uint32(lane_canon32(t9.L3))}).L3 >> 24))
	t10 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(32))) : uint64(uint32(i32(32)))+8])[:]))
	return t10
}
func (m *Module) Xop147(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	_ = v3
	t11 := vec128{(uint32(lane_canon32(t9.L1))), (uint32(lane_canon32(t9.L0))), (uint32(lane_canon32(t9.L2))), (uint32(lane_canon32(t9.L3)))}
	v2 = t11
	t12 := v2
	t13 := int32(t12.L0)
	t14 := int64(uint32(t13))
	t15 := v2
	t16 := int32(t15.L1)
	return t14 | int64(uint32(t16))<<32
}
func (m *Module) Xop148(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := vec128{(uint32(lane_canon32(t9.L0))) ^ (lane_u32(0x0)), (uint32(lane_canon32(t9.L1))) ^ (lane_u32(0x80000000)), (uint32(lane_canon32(t9.L2))) ^ (lane_u32(0x0)), (uint32(lane_canon32(t9.L3))) ^ (lane_u32(0x0))}
	v2 = t10
	t11 := v2
	t12 := int32(t11.L0)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L1)
	return t13 | int64(uint32(t15))<<32
}
func (m *Module) Xop149(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := math.Float32frombits(uint32(int32(v1)))
	t11 := vec128{math.Float32bits((t10)), math.Float32bits((t10)), math.Float32bits((t10)), math.Float32bits((t10))}
	t12 := math.Float32frombits(uint32(int32(v0)))
	t13 := vec128{t11.L0, math.Float32bits((t12)), t11.L2, t11.L3}
	t14 := vec128{uint32(lane_pmin32((uint32(lane_canon32(t9.L0))), t13.L0)), uint32(lane_pmin32((uint32(lane_canon32(t9.L1))), t13.L1)), uint32(lane_pmin32((uint32(lane_canon32(t9.L2))), t13.L2)), uint32(lane_pmin32((uint32(lane_canon32(t9.L3))), t13.L3))}
	v2 = t14
	t15 := v2
	t16 := int32(t15.L0)
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(t18.L1)
	return t17 | int64(uint32(t19))<<32
}
func (m *Module) Xop150(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := vec128{math.Float32bits((math.Float32frombits(0x3f800000))), (uint32(lane_canon32(t9.L1))), (uint32(lane_canon32(t9.L2))), (uint32(lane_canon32(t9.L3)))}
	v2 = t10
	t11 := v2
	t12 := int32(t11.L0)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L1)
	return t13 | int64(uint32(t15))<<32
}
func (m *Module) Xop151(v0, v1 int64) int64 {
	var v2, v3, v4 vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) * math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) * math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) * math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) * math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t9.L0) + math.Float32frombits((lane_u32(0xbf800000)))))), uint32(math.Float32bits(float32(math.Float32frombits(t9.L1) + math.Float32frombits((lane_u32(0xbf800000)))))), uint32(math.Float32bits(float32(math.Float32frombits(t9.L2) + math.Float32frombits((lane_u32(0xbf800000)))))), uint32(math.Float32bits(float32(math.Float32frombits(t9.L3) + math.Float32frombits((lane_u32(0xbf800000))))))}
	v4 = t10
	t11 := v4
	t12 := vec128{uint32((uint32(lane_canon32(t11.L0))) ^ (1 << 31)), uint32((uint32(lane_canon32(t11.L1))) ^ (1 << 31)), uint32((uint32(lane_canon32(t11.L2))) ^ (1 << 31)), uint32((uint32(lane_canon32(t11.L3))) ^ (1 << 31))}
	v2 = t12
	t13 := v2
	t14 := int32(t13.L0)
	t15 := int64(uint32(t14))
	t16 := v2
	t17 := int32(t16.L1)
	return t15 | int64(uint32(t17))<<32
}
func (m *Module) Xop152(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(math.Float32bits(float32(math.Float32frombits(t3.L0) + math.Float32frombits(t7.L0)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L1) + math.Float32frombits(t7.L1)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L2) + math.Float32frombits(t7.L2)))), uint32(math.Float32bits(float32(math.Float32frombits(t3.L3) + math.Float32frombits(t7.L3))))}
	v3 = t8
	t9 := v3
	t10 := vec128{uint32(math.Float64bits(float64(math.Float32frombits(t9.L0)))), uint32((math.Float64bits(float64(math.Float32frombits(t9.L0)))) >> 32), uint32(math.Float64bits(float64(math.Float32frombits(t9.L1)))), uint32((math.Float64bits(float64(math.Float32frombits(t9.L1)))) >> 32)}
	t11 := vec128{uint32(uint64((uint64((uint32(uint64(lane_canon64((uint64(t10.L0) | uint64(t10.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t10.L0) | uint64(t10.L1)<<32))))>>32)))<<32) ^ (1 << 63))), uint32((uint64((uint64((uint32(uint64(lane_canon64((uint64(t10.L0) | uint64(t10.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t10.L0) | uint64(t10.L1)<<32))))>>32)))<<32) ^ (1 << 63))) >> 32), uint32(uint64((uint64((uint32(uint64(lane_canon64((uint64(t10.L2) | uint64(t10.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t10.L2) | uint64(t10.L3)<<32))))>>32)))<<32) ^ (1 << 63))), uint32((uint64((uint64((uint32(uint64(lane_canon64((uint64(t10.L2) | uint64(t10.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t10.L2) | uint64(t10.L3)<<32))))>>32)))<<32) ^ (1 << 63))) >> 32)}
	v2 = t11
	t12 := v2
	t13 := int64((uint64(t12.L0) | uint64(t12.L1)<<32))
	t14 := v2
	t15 := int64((uint64(t14.L2) | uint64(t14.L3)<<32))
	return t13 + i64_rotl(t15, int64(17))
}
func (m *Module) Xop153(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v3 = t8
	t9 := v3
	t10 := vec128{uint32(uint64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32) ^ (1 << 63))), uint32((uint64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32) ^ (1 << 63))) >> 32), uint32(uint64((uint64((uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32))))>>32)))<<32) ^ (1 << 63))), uint32((uint64((uint64((uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32))))>>32)))<<32) ^ (1 << 63))) >> 32)}
	v2 = t10
	t11 := v2
	t12 := int64((uint64(t11.L0) | uint64(t11.L1)<<32))
	t13 := v2
	t14 := int64((uint64(t13.L2) | uint64(t13.L3)<<32))
	return t12 + i64_rotl(t14, int64(17))
}
func (m *Module) Xop154(v0, v1 int64) int64 {
	var q16 *[16]byte
	mem := m.memory
	var _, v3, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v3 = t8
	t9 := v3
	q16 = (*[16]byte)(mem[uint64(uint32(int32(48))) : uint64(uint32(int32(48)))+16])
	q16[0] = byte((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L0)
	q16[1] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L0 >> 8))
	q16[2] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L0 >> 16))
	q16[3] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L0 >> 24))
	q16[4] = byte((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L1)
	q16[5] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L1 >> 8))
	q16[6] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L1 >> 16))
	q16[7] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L1 >> 24))
	q16[8] = byte((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L2)
	q16[9] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L2 >> 8))
	q16[10] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L2 >> 16))
	q16[11] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L2 >> 24))
	q16[12] = byte((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L3)
	q16[13] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L3 >> 8))
	q16[14] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L3 >> 16))
	q16[15] = byte(((vec128{uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32), uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))), uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)}).L3 >> 24))
	t10 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(48))) : uint64(uint32(i32(48)))+8])[:]))
	t11 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(56))) : uint64(uint32(i32(56)))+8])[:]))
	return t10 + i64_rotl(t11, int64(17))
}
func (m *Module) Xop155(v0, v1 int64) int64 {
	var v2, v3, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) + math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) + math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v3 = t8
	t9 := v3
	t10 := vec128{uint32((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))) ^ (1 << 31)), uint32((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))) >> 32)) ^ (1 << 31)), uint32((uint32(uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32))))) ^ (1 << 31)), uint32((uint32((uint64(lane_canon64((uint64(t9.L2) | uint64(t9.L3)<<32)))) >> 32)) ^ (1 << 31))}
	v2 = t10
	t11 := v2
	t12 := int32(t11.L0)
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(t14.L1)
	return t13 | int64(uint32(t15))<<32
}
