// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && amd64.v3 && go1.27 && !go1.28

package functions2

import "simd/archsimd"

type vec128 = archsimd.Uint32x4

func Fn7(v0 int32, v1, v2 vec128) vec128 {
	t1 := v1
	var p0 vec128
	{
		p2 := v2
		if v0 != 0 {
			p2 = t1
		}
		t3 := p2.Add((vec128{}))
		p0 = t3
	}
	return p0
}
