// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions2

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func Fn7(v0 int32, v1, v2 vec128) vec128 {
	t1 := v1
	var p0 vec128
	{
		p2 := v2
		if v0 != 0 {
			p2 = t1
		}
		t3 := vec128{uint32(p2.L0 + (lane_u32(0x0))), uint32(p2.L1 + (lane_u32(0x0))), uint32(p2.L2 + (lane_u32(0x0))), uint32(p2.L3 + (lane_u32(0x0)))}
		p0 = t3
	}
	return p0
}

// Prevents constant folding, as i32 does.
//
//go:nosplit
func lane_u32(x uint32) uint32 { return x }
