// Code generated by wasm2go. DO NOT EDIT.

package functions26

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop43(m *instance.Module, v0, v1 int64) int64 {
	return i64_trunc_sat_f32_u(math.Float32frombits(uint32(int32(v0))))
}

//go:nosplit
func i64_trunc_sat_f32_u(f float32) int64 {
	var i uint64
	switch {
	case f <= 0 || f != f:
		i = 0
	case f >= math.MaxUint64:
		i = math.MaxUint64
	default:
		i = uint64(f)
	}
	return int64(i)
}
