// Code generated by wasm2go. DO NOT EDIT.

package functions61

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func Xop95(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128{math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0)), math.Float32bits((t0))}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128{t1.L0, math.Float32bits((t2)), t1.L2, t1.L3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128{math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4)), math.Float32bits((t4))}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128{t5.L0, math.Float32bits((t6)), t5.L2, t5.L3}
	t8 := vec128{uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L0), math.Float32frombits(t7.L0))))), uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L1), math.Float32frombits(t7.L1))))), uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L2), math.Float32frombits(t7.L2))))), uint32(lane_canon32(math.Float32bits(min(math.Float32frombits(t3.L3), math.Float32frombits(t7.L3)))))}
	v2 = t8
	t9 := v2
	t10 := int32(t9.L0)
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.L1)
	return t11 | int64(uint32(t13))<<32
}

// The bits of a float32 lane, with a NaN made the positive canonical NaN,
// without a branch: the mask is all ones exactly when the magnitude is
// above the infinity's.
//
//go:nosplit
func lane_canon32(b uint32) uint32 {
	return b ^ (b^0x7fc00000)&-((b&0x7fffffff+0x7fffff)>>31)
}
