// Code generated by wasm2go. DO NOT EDIT.

//go:build 386 || amd64 || arm64 || loong64 || ppc64le || wasm

package bump

import (
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	memory     []byte
	memBacking []byte
	maxMem     int64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 1024
	m.memBacking = make([]byte, 0x20000)
	m.memory = m.memBacking
	memory_init(m.memory, data0, uint32(i32(65536)), 0, len(data0))
	return m
}

// MemoryMax is the most bytes the module's memory can grow to
// through its own memory.grow: its declared maximum.
func (m *Module) MemoryMax() int64 { return 67108864 }

// UseMemory moves the module's memory to the start of buf's backing array,
// where it keeps its size and contents and grows in place, without
// copying or allocating, as far as buf's capacity allows (past it, it moves
// to a new array in the Go heap). buf's bytes past the memory's size must
// be zero, and nothing else may write to them. UseMemory returns false,
// and leaves the memory where it is, when buf's capacity is less than the
// memory's size (a nil buf included). Slices of the memory taken before
// the call are stale after it, as after the memory grows.
func (m *Module) UseMemory(buf []byte) bool {
	n := len(m.memory)
	if cap(buf) < n {
		return false
	}
	buf = buf[:cap(buf)]
	copy(buf, m.memory)
	m.memBacking = buf
	m.memory = buf[:n:n]
	return true
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory Module

func (m *wasmMemory) Slice() *[]byte { return &m.memory }

func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow(&m.memory, &m.memBacking, delta, max)
}
func (m *Module) Xfree(v0 int32) {
	mem := m.memory
	if v0 == 0 {
		return
	}
	t0 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65544)))+3]), -3)))
	if v0 != t0 {
		return
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)) = uint32(v0)
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(uint32(i32(65544))))) = uint32(i32(0))
}
func (m *Module) Xmalloc(v0 int32) int32 {
	mem := m.memory
	var v1, v2, v3, v4, v5, v6 int32
	{
		if v0 <= int32(0) {
			goto l0
		}
		v3 = (v0 + int32(15)) & int32(-16)
		t0 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65540)))+3]), -3)))
		v1 = t0
		t1 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)))
		v2 = t1
		v0 = v2
	l2:
		v0 = v1 - v0
		if uint32(v0) < uint32(v3) {
			v5 = v3 - v0 + int32(0xffff)
			v6 = int32(uint32(v5) >> 16)
			t2 := int32(memory_grow(&m.memory, &m.memBacking, int64(v6), m.maxMem))
			mem = m.memory
			v4 = t2
			if v4 == int32(-1) {
				goto l0
			}
			t3 := v1
			v0 = v4 << 16
			if t3 != v0 {
				*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)) = uint32(v0)
				v1 = (v4 + v6) << 16
				*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65540)))+3]), -3)) = uint32(v1)
				v2 = v0
				goto l2
			}
			*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65540)))+3]), -3)) = uint32(v1 + v5&int32(-65536))
		}
		*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65544)))+3]), -3)) = uint32(v2)
		*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)) = uint32(v2 + v3)
		return v2
	}
l0:
	return int32(0)
}
func (m *Module) Xmemalign(v0, v1 int32) int32 {
	mem := m.memory
	var v2, v3 int32
	{
		var p0 int32
		if int32(bits.OnesCount32(uint32(v0))) != int32(1) {
			p0 = 1
		}
		var p1 int32
		if v1 <= int32(0) {
			p1 = 1
		}
		if p0|p1 != 0 {
			goto l0
		}
		if uint32(v0) <= uint32(int32(16)) {
			t2 := m.Xmalloc(v1)
			mem = m.memory
			return t2
		}
		t3 := m.Xmalloc(v0 + v1 - int32(16))
		mem = m.memory
		v3 = t3
		if v3 == 0 {
			goto l0
		}
		v2 = (v0 + v3 - int32(1)) & (int32(0) - v0)
		*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65544)))+3]), -3)) = uint32(v2)
		*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)) = uint32((v1 + v2 + int32(15)) & int32(-16))
	}
l0:
	return v2
}
func (m *Module) Xrealloc(v0, v1 int32) int32 {
	mem := m.memory
	var v2, v3 int32
	if v0 == 0 {
		t0 := m.Xmalloc(v1)
		mem = m.memory
		return t0
	}
	{
		if v1 == 0 {
			t1 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65544)))+3]), -3)))
			if v0 != t1 {
				goto l0
			}
			*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)) = uint32(v0)
			*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(uint32(i32(65544))))) = uint32(i32(0))
			return int32(0)
		}
		t2 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65544)))+3]), -3)))
		v2 = t2
		var p3 int32
		if v2 == v0 {
			p3 = 1
		}
		var p4 int32
		if uint32(v1) > uint32(int32(16)) {
			p4 = 1
		}
		if p3|p4 == 0 {
			return v0
		}
		t5 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)))
		v3 = t5
		if v0 == v2 {
			*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(uint32(i32(65536))))) = uint32(v0)
		}
		t6 := m.Xmalloc(v1)
		mem = m.memory
		v2 = t6
		if v2 == 0 {
			*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(i32(65536)))+3]), -3)) = uint32(v3)
			return int32(0)
		}
		if v0 == v2 {
			goto l0
		}
		v3 = v3 - v0
		p7 := v1
		if uint32(v1) > uint32(v3) {
			p7 = v3
		}
		v1 = p7
		if v1 == 0 {
			goto l0
		}
		memory_copy(mem, uint32(v2), uint32(v0), uint32(v1))
	}
l0:
	return v2
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(m)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(mem[addr:])
	}
	_ = mem[uint64(addr)+3]
	val := *(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr)))
	if big {
		return bits.ReverseBytes32(val)
	}
	return val
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	_ = mem[uint64(addr)+3]
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func store32u[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func i32(x int32) int32 { return x }

// Grows the memory *mem by delta pages, up to max, and returns its old size
// in pages, or -1. *back is the memory's backing array: *mem is its prefix,
// with its capacity cut to its length, so no slice of the memory reaches
// past its end, and back's bytes past the memory's end are zero. Growth
// within back is in place: no copy, no allocation. Past it, the memory moves
// to a new backing array of twice the size, at least what the growth needs,
// at most max pages.
func memory_grow(mem, back *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	size := int(new << 16)
	if size > cap(*back) {
		n := int(min(uint64(cap(*back))>>15, uint64(max)) << 16)
		if n < size {
			n = size
		}
		b := make([]byte, n)
		copy(b, buf)
		*back = b
	}
	*mem = (*back)[:size:size]
	return int64(old)
}

func memory_init[T1, T2 int | uint32 | uint64](mem []byte, data string, dest T1, src, n T2) {
	mem = mem[:len(mem):len(mem)]
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], data[z:w])
}

func memory_copy[T uint32 | uint64](mem []byte, dest, src, n T) {
	mem = mem[:len(mem):len(mem)]
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(mem[x:y], mem[z:w])
}

const data0 = "\x10\x00\x01\x00\x00\x00\x02"
