// Code generated by wasm2go. DO NOT EDIT.

package functions7

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func Fn2(v0 vec128) vec128 {
	t0 := v0
	t1 := vec128{uint32(-t0.L0), uint32(-t0.L1), uint32(-t0.L2), uint32(-t0.L3)}
	return t1
}
