// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions7

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Fn2(v0 vec128) vec128 {
	t0 := v0
	t1 := vec128{uint32(-t0.L0), uint32(-t0.L1), uint32(-t0.L2), uint32(-t0.L3)}
	return t1
}
