// Code generated by wasm2go. DO NOT EDIT.

package functions1

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/stack_bound/internal/functions2"
	"github.com/stricttools/wasm-to-go/testdata/packages/stack_bound/internal/instance"
)

func Fn8(m *instance.Module, v0 int32) int32 {
	t0 := functions2.Fn7(m, v0)
	return t0
}
