// Code generated by wasm2go. DO NOT EDIT.

//go:build !(386 || amd64 || arm64 || loong64 || ppc64le || wasm)

package functions5

import (
	"encoding/binary"
	"github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/instance"
)

func Xinc(m *instance.Module, v0 int32) {
	mem := m.Memory
	t0 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
	binary.LittleEndian.PutUint32(mem[uint32(v0):], uint32(t0+int32(1)))
}
