// Code generated by wasm2go. DO NOT EDIT.

package functions1

import "github.com/stricttools/wasm-to-go/testdata/packages/loops/internal/instance"

func Xfirst_power_over_limit(m *instance.Module, v0, v1 int32) int32 {
	var v2 int32
	v2 = int32(1)
l1:
	if v2 > v1 {
		return v2
	}
	v2 = v2 * v0
	goto l1
}
