// Code generated by wasm2go. DO NOT EDIT.

package functions107

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop51(m *instance.Module, v0, v1 int64) int64 {
	return int64(math.Float64bits(float64(uint32(int32(v0)))))
}
