// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && amd64.v3 && go1.27 && !go1.28

package functions20

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"simd/archsimd"
)

type vec128 = archsimd.Uint32x4

func Xop136(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := int32(v0)
	t1 := archsimd.BroadcastUint32x4(uint32((t0)))
	t2 := int32(v1)
	t3 := t1.SetElem(1, uint32((t2)))
	t4 := vec128{}.SetElem(0, math.Float32bits(float32(t3.GetElem(0)))).SetElem(1, math.Float32bits(float32(t3.GetElem(1)))).SetElem(2, math.Float32bits(float32(t3.GetElem(2)))).SetElem(3, math.Float32bits(float32(t3.GetElem(3))))
	v2 = t4
	t5 := v2
	t6 := int32(t5.GetElem(0))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.GetElem(1))
	return t7 | int64(uint32(t9))<<32
}
