// Code generated by wasm2go. DO NOT EDIT.

package functions2

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop89(m *instance.Module, v0, v1 int64) int64 {
	var _, _ float64
	var v4, _ float32
	var _ int32
	v4 = float32(math.Float32frombits(uint32(int32(v0))) + math.Float32frombits(uint32(int32(v1))))
	return int64(math.Float64bits(f64_neg(f64_canon(float64(v4)))))
}

//go:nosplit
func f64_neg(x float64) float64 {
	return math.Float64frombits(math.Float64bits(x) ^ 1<<63)
}

//go:nosplit
func f64_canon(x float64) float64 {
	if x != x {
		return math.Float64frombits(0x7ff8000000000000)
	}
	return x
}
