// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions2

import (
	"encoding/binary"
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"math/bits"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Xop154(m *instance.Module, v0, v1 int64) int64 {
	var q16 *[16]byte
	mem := m.Memory
	var _, _ vec128
	var v3 vec128f64
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128f64{(t4), (t4)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128f64{t5.D0, (t6)}
	t8 := vec128f64{float64(t3.D0 + t7.D0), float64(t3.D1 + t7.D1)}
	v3 = t8
	t9 := v3
	q16 = (*[16]byte)(mem[uint64(uint32(int32(48))) : uint64(uint32(int32(48)))+16])
	q16[0] = byte(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))))
	q16[1] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 8))
	q16[2] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 16))
	q16[3] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 24))
	q16[4] = byte(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0)))))) >> 32))
	q16[5] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32) >> 8))
	q16[6] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32) >> 16))
	q16[7] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D0))))))>>32) >> 24))
	q16[8] = byte(uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))))
	q16[9] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 8))
	q16[10] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 16))
	q16[11] = byte((uint32(math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 24))
	q16[12] = byte(uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1)))))) >> 32))
	q16[13] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32) >> 8))
	q16[14] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32) >> 16))
	q16[15] = byte((uint32((math.Float64bits((math.Float64frombits(lane_canon64(math.Float64bits(t9.D1))))))>>32) >> 24))
	t10 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(48))) : uint64(uint32(i32(48)))+8])[:]))
	t11 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(56))) : uint64(uint32(i32(56)))+8])[:]))
	return t10 + i64_rotl(t11, int64(17))
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64_rotl(x, y int64) int64 {
	return int64(bits.RotateLeft64(uint64(x), int(y)))
}

//go:nosplit
func lane_canon64(b uint64) uint64 {
	return b ^ (b^0x7ff8000000000000)&-((b&0x7fffffffffffffff+0xfffffffffffff)>>63)
}
