// Code generated by wasm2go. DO NOT EDIT.

package functions41

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop28(m *instance.Module, v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_max(math.Float32frombits(uint32(int32(v0))), math.Float32frombits(uint32(int32(v1))))))))
}

//go:nosplit
func f32_max(x, y float32) float32 {
	if m := max(x, y); m == m {
		return m
	}
	return math.Float32frombits(0x7fc00000)
}
