// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && amd64.v3 && go1.27 && !go1.28

package functions17

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"simd/archsimd"
)

type vec128 = archsimd.Uint32x4

func Xop139(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := archsimd.BroadcastUint32x4(math.Float32bits((t0)))
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := t1.SetElem(1, math.Float32bits((t2)))
	t4 := vec128{}.SetElem(0, uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.GetElem(0))))).SetElem(1, uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.GetElem(1))))).SetElem(2, uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.GetElem(2))))).SetElem(3, uint32(i32_trunc_sat_f32_s(math.Float32frombits(t3.GetElem(3)))))
	v2 = t4
	t5 := v2
	t6 := int32(t5.GetElem(0))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.GetElem(1))
	return t7 | int64(uint32(t9))<<32
}

// Returns x, an integer of magnitude below 2^51 (the caller has checked
// it), as an int64. Adding 1.5 * 2^52 is exact for such an x, and leaves it
// in the significand's low bits, offset by the constant's own bits: two
// instructions beside the addition, fewer than a shift by the exponent.
//
//go:nosplit
func trunc_small(x float64) int64 {
	return int64(math.Float64bits(x+0x1.8p52)) - 0x4338000000000000
}

//go:nosplit
func i32_trunc_sat_f32_s(f float32) int32 {
	switch {
	case f <= math.MinInt32:
		return math.MinInt32
	case f >= math.MaxInt32:
		return math.MaxInt32
	case f != f:
		return 0
	}
	return int32(trunc_small(math.Trunc(float64(f))))
}
