// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions17

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Xop139(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := vec128{uint32(i32_trunc_sat_f32_s(t3.F0)), uint32(i32_trunc_sat_f32_s(t3.F1)), uint32(i32_trunc_sat_f32_s(t3.F2)), uint32(i32_trunc_sat_f32_s(t3.F3))}
	v2 = t4
	t5 := v2
	t6 := int32(t5.L0)
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(t8.L1)
	return t7 | int64(uint32(t9))<<32
}

// Returns x, an integer of magnitude below 2^51 (the caller has checked
// it), as an int64. Adding 1.5 * 2^52 is exact for such an x, and leaves it
// in the significand's low bits, offset by the constant's own bits: two
// instructions beside the addition, fewer than a shift by the exponent.
//
//go:nosplit
func trunc_small(x float64) int64 {
	return int64(math.Float64bits(x+0x1.8p52)) - 0x4338000000000000
}

//go:nosplit
func i32_trunc_sat_f32_s(f float32) int32 {
	switch {
	case f <= math.MinInt32:
		return math.MinInt32
	case f >= math.MaxInt32:
		return math.MaxInt32
	case f != f:
		return 0
	}
	return int32(trunc_small(math.Trunc(float64(f))))
}
