// Code generated by wasm2go. DO NOT EDIT.

//go:build !(386 || amd64 || arm64 || loong64 || ppc64le || wasm)

package sjlj

import (
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	t0       []any
	elements [][]any
	memory   []byte
	maxMem   int64
	g0       int32
}

func New() *Module {
	m := new(Module)
	m.t0 = make([]any, 2)
	m.maxMem = 65536
	m.memory = make([]byte, 0x20000)
	m.elements = [][]any{{m.fn3}}
	table_init(m.t0, m.elements[0], i32(1), 0, len(m.elements[0]))
	m.elements[0] = nil
	m.g0 = i32(65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xtest() int32 {
	mem := m.memory
	var v0, v1, v2 int32
	t0 := m.g0
	v1 = t0 - int32(16)
	m.g0 = v1
	binary.LittleEndian.PutUint32(mem[uint32(i32(65540)):], uint32(int32(1)))
	binary.LittleEndian.PutUint32(mem[uint32(i32(65536)):], uint32(v1+int32(12)))
l2:
	if v0 == 0 {
		binary.LittleEndian.PutUint32(mem[uint32(i32(65544)):], uint32(int32(0)))
		m._invoke_vii(int32(1), int32(65536), int32(42))
		mem = m.memory
		t1 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(65544)):]))
		v0 = t1
		binary.LittleEndian.PutUint32(mem[uint32(i32(65544)):], uint32(int32(0)))
		{
			if v0 == 0 {
				goto l0
			}
			t2 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(65548)):]))
			v2 = t2
			if v2 == 0 {
				goto l0
			}
			t3 := int32(binary.LittleEndian.Uint32(mem[uint32(v0):]))
			var p4 int32
			if t3 == v1+int32(12) {
				t5 := int32(binary.LittleEndian.Uint32(mem[uint64(uint32(v0))+4:]))
				p4 = t5
			} else {
				p4 = int32(0)
			}
			if p4 == 0 {
				m.fn3(v0, v2)
				panic("unreachable")
			}
			binary.LittleEndian.PutUint32(mem[uint32(i32(65552)):], uint32(v2))
		}
	l0:
		t6 := int32(binary.LittleEndian.Uint32(mem[uint32(i32(65552)):]))
		v0 = t6
		goto l2
	}
	m.g0 = v1 + int32(16)
	return v0
}
func (m *Module) fn3(v0, v1 int32) {
	mem := m.memory
	binary.LittleEndian.PutUint32(mem[uint32(i32(65544)):], uint32(v0))
	p0 := v1
	if uint32(v1) <= uint32(int32(1)) {
		p0 = int32(1)
	}
	binary.LittleEndian.PutUint32(mem[uint32(i32(65548)):], uint32(p0))
	m.__throw_longjmp()
}
func (m *Module) X__indirect_function_table() *[]any {
	return &m.t0
}
func (m *Module) X__stack_pointer() *int32 {
	return &m.g0
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

func (m *Module) __throw_longjmp() { panic("emscripten_longjmp") }
func (m *Module) __catch_longjmp(sp int32) {
	if r := recover(); r == "emscripten_longjmp" {
		*m.X__stack_pointer() = sp
	} else if r != nil {
		panic(r)
	}
}
func (m *Module) _invoke_vii(idx int32, v1 int32, v2 int32) {
	defer m.__catch_longjmp(*m.X__stack_pointer())
	(*m.X__indirect_function_table())[idx].(func(int32, int32))(v1, v2)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(mem[addr:])
	}
	_ = mem[uint64(addr)+3]
	val := *(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr)))
	if big {
		return bits.ReverseBytes32(val)
	}
	return val
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	_ = mem[uint64(addr)+3]
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func store32u[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func i32(x int32) int32 { return x }

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	*mem = append(buf, make([]byte, int(new<<16)-len)...)
	return int64(old)
}

func table_init[T1, T2, T3 int | int32 | int64](tab, elems []any, dest T1, src T2, n T3) {
	x := uint64(dest)
	z := uint64(src)
	y := x + uint64(n)
	w := z + uint64(n)
	copy(tab[x:y], elems[z:w])
}
