// Code generated by wasm2go. DO NOT EDIT.

package instance
// Module is the state of an instance of the module: the output package's Module holds one.
type Module struct {
}
// The functions called from a package that precedes theirs, set by the output package when it is initialized.
var Xis_even func(m *Module, v0 int32) int32
