// Code generated by wasm2go. DO NOT EDIT.

package functions69

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop24(m *instance.Module, v0, v1 int64) int64 {
	return int64(uint32(int32(math.Float32bits(f32_canon(float32(math.Float32frombits(uint32(int32(v0))) - math.Float32frombits(uint32(int32(v1)))))))))
}

//go:nosplit
func f32_canon(x float32) float32 {
	if x != x {
		return math.Float32frombits(0x7fc00000)
	}
	return x
}
