// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && arm64 && go1.27 && !go1.28

package functions60

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"simd/archsimd"
)

type vec128 = archsimd.Uint32x4

func Xop96(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := archsimd.BroadcastUint32x4(math.Float32bits((t0)))
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := t1.SetElem(1, math.Float32bits((t2)))
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := archsimd.BroadcastUint32x4(math.Float32bits((t4)))
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := t5.SetElem(1, math.Float32bits((t6)))
	t8 := archsimd.BroadcastUint32x4(0x7fc00000).IfElse(t3.BitsToFloat32().NotEqual(t3.BitsToFloat32()).Or(t7.BitsToFloat32().NotEqual(t7.BitsToFloat32())), t3.BitsToFloat32().Max(t7.BitsToFloat32()).ToBits())
	v2 = t8
	t9 := v2
	t10 := int32(t9.GetElem(0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(t12.GetElem(1))
	return t11 | int64(uint32(t13))<<32
}
