// Code generated by wasm2go. DO NOT EDIT.

package functions36

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop33(m *instance.Module, v0, v1 int64) int64 {
	t0 := i32_trunc_f64_u(math.Float64frombits(uint64(v0)))
	return int64(uint32(t0))
}

//go:nosplit
func i32_trunc_f64_u(f float64) int32 {
	x := math.Trunc(f)
	switch {
	case f != f:
		panic("invalid conversion to integer")
	case x < 0 || x > math.MaxUint32:
		panic("integer overflow")
	}
	return int32(uint32(x))
}
