// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && amd64.v3 && go1.27 && !go1.28

package functions11

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"simd/archsimd"
)

type vec128 = archsimd.Uint32x4

func Xop145(m *instance.Module, v0, v1 int64) int64 {
	var _, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := archsimd.BroadcastUint32x4(math.Float32bits((t0)))
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := t1.SetElem(1, math.Float32bits((t2)))
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := archsimd.BroadcastUint32x4(math.Float32bits((t4)))
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := t5.SetElem(1, math.Float32bits((t6)))
	t8 := t3.BitsToFloat32().Add(t7.BitsToFloat32()).ToBits()
	v3 = t8
	t9 := v3
	t10 := math.Float32frombits((archsimd.BroadcastUint32x4(0x7fc00000).IfElse(t9.BitsToFloat32().NotEqual(t9.BitsToFloat32()), t9)).GetElem(1))
	return int64(uint32(int32(math.Float32bits(t10))))
}
