// Code generated by wasm2go. DO NOT EDIT.

package functions4

import "github.com/stricttools/wasm-to-go/testdata/packages/simd_api/internal/instance"

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func XimportedLane(m *instance.Module) int32 {
	t0 := vec128{(uint32((*m.G0)[0])<<0 | uint32((*m.G0)[1])<<8 | uint32((*m.G0)[2])<<16 | uint32((*m.G0)[3])<<24), (uint32((*m.G0)[4])<<0 | uint32((*m.G0)[5])<<8 | uint32((*m.G0)[6])<<16 | uint32((*m.G0)[7])<<24), (uint32((*m.G0)[8])<<0 | uint32((*m.G0)[9])<<8 | uint32((*m.G0)[10])<<16 | uint32((*m.G0)[11])<<24), (uint32((*m.G0)[12])<<0 | uint32((*m.G0)[13])<<8 | uint32((*m.G0)[14])<<16 | uint32((*m.G0)[15])<<24)}
	t1 := int32(t0.L2)
	return t1
}
