// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import "encoding/binary"

// A Module must be created by New.
// Its functions load the imported memory New sets up when they start.
type Module struct {
	memory *[]byte
	memImp Memory
	maxMem int64
	_env   Xenv
}

func New(v0 Xenv) *Module {
	m := new(Module)
	m._env = v0
	m.maxMem = 10
	m.memImp = v0.Xmemory()
	m.memory = m.memImp.Slice()
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xenv = interface {
	Xmemory() Memory
}
type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}

func (m *Module) Xld16(v0 int32) int32 {
	mem := *m.memory
	t0 := int32(binary.LittleEndian.Uint16((*[2]byte)(mem[:len(mem):len(mem)][uint64(uint32(v0)) : uint64(uint32(v0))+2])[:]))
	return t0
}
func (m *Module) Xld32(v0 int32) int32 {
	mem := *m.memory
	t0 := int32(binary.LittleEndian.Uint32((*[4]byte)(mem[:len(mem):len(mem)][uint64(uint32(v0)) : uint64(uint32(v0))+4])[:]))
	return t0
}
func (m *Module) Xld64(v0 int32) int64 {
	mem := *m.memory
	t0 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[:len(mem):len(mem)][uint64(uint32(v0)) : uint64(uint32(v0))+8])[:]))
	return t0
}
func (m *Module) Xld32o(v0 int32) int32 {
	mem := *m.memory
	t0 := int32(binary.LittleEndian.Uint32((*[4]byte)(mem[:len(mem):len(mem)][uint64(uint32(v0))+0xa0000 : uint64(uint32(v0))+0xa0000+4])[:]))
	return t0
}
func (m *Module) Xst32(v0, v1 int32) {
	mem := *m.memory
	binary.LittleEndian.PutUint32((*[4]byte)(mem[:len(mem):len(mem)][uint64(uint32(v0)) : uint64(uint32(v0))+4])[:], uint32(v1))
}
func (m *Module) Xst64(v0 int32, v1 int64) {
	mem := *m.memory
	binary.LittleEndian.PutUint64((*[8]byte)(mem[:len(mem):len(mem)][uint64(uint32(v0)) : uint64(uint32(v0))+8])[:], uint64(v1))
}
func (m *Module) Xgrow(v0 int32) int32 {
	t0 := int32(m.memImp.Grow(int64(v0), m.maxMem))
	return t0
}

//go:nosplit
func load16[T uint32 | uint64](mem []byte, addr T) uint16 {
	return binary.LittleEndian.Uint16(mem[addr:])
}

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	return binary.LittleEndian.Uint32(mem[addr:])
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	binary.LittleEndian.PutUint32(mem[addr:], val)
}

//go:nosplit
func load64[T uint32 | uint64](mem []byte, addr T) uint64 {
	return binary.LittleEndian.Uint64(mem[addr:])
}

//go:nosplit
func store64[T uint32 | uint64](mem []byte, addr T, val uint64) {
	binary.LittleEndian.PutUint64(mem[addr:], val)
}
