// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && wasm && go1.27 && !go1.28

package functions10

import (
	"encoding/binary"
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"simd/archsimd"
)

type vec128 = archsimd.Uint32x4

func Xop146(m *instance.Module, v0, v1 int64) int64 {
	var q16 *[16]byte
	mem := m.Memory
	var _, v3, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := archsimd.BroadcastUint32x4(math.Float32bits((t0)))
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := t1.SetElem(1, math.Float32bits((t2)))
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := archsimd.BroadcastUint32x4(math.Float32bits((t4)))
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := t5.SetElem(1, math.Float32bits((t6)))
	t8 := t3.BitsToFloat32().Add(t7.BitsToFloat32()).ToBits()
	v3 = t8
	t9 := v3
	q16 = (*[16]byte)(mem[uint64(uint32(int32(32))) : uint64(uint32(int32(32)))+16])
	(archsimd.BroadcastUint32x4(0x7fc00000).IfElse(t9.BitsToFloat32().NotEqual(t9.BitsToFloat32()), t9)).ReshapeToUint8s().StoreArray(q16)
	t10 := int64(binary.LittleEndian.Uint64((*[8]byte)(mem[uint64(uint32(i32(32))) : uint64(uint32(i32(32)))+8])[:]))
	return t10
}

//go:nosplit
func i32(x int32) int32 { return x }
