// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

type Module struct {
	g0 int32
}

func New() *Module {
	m := new(Module)
	m.g0 = i32(0)
	return m
}
func (m *Module) fn0() int32 {
	t0 := m.g0
	m.g0 = t0 + int32(1)
	return int32(100)
}
func (m *Module) Xtest(v0 int32) int32 {
	t0 := m.fn0()
	p1 := int32(5)
	if v0 != 0 {
		p1 = t0
	}
	return p1
}
func (m *Module) Xcounter() int32 {
	t0 := m.g0
	return t0
}

//go:nosplit
func i32(x int32) int32 { return x }
