// Code generated by wasm2go. DO NOT EDIT.

package functions1

import "github.com/stricttools/wasm-to-go/testdata/packages/simd_api/internal/instance"

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func Xsum(m *instance.Module, v0 int32) int32 {
	var q16 *[16]byte
	mem := m.Memory
	var v1 vec128
	var v2 int32
l1:
	{
		if v0 == 0 {
			t4 := v1
			t5 := int32(t4.L0)
			t6 := v1
			t7 := int32(t6.L1)
			t8 := t5 + t7
			t9 := v1
			t10 := int32(t9.L2)
			t11 := v1
			t12 := int32(t11.L3)
			return t8 + (t10 + t12)
		}
		t0 := v1
		t1 := v2
		q16 = (*[16]byte)(mem[uint64(uint32(t1)) : uint64(uint32(t1))+16])
		t2 := vec128{(uint32(q16[0])<<0 | uint32(q16[1])<<8 | uint32(q16[2])<<16 | uint32(q16[3])<<24), (uint32(q16[4])<<0 | uint32(q16[5])<<8 | uint32(q16[6])<<16 | uint32(q16[7])<<24), (uint32(q16[8])<<0 | uint32(q16[9])<<8 | uint32(q16[10])<<16 | uint32(q16[11])<<24), (uint32(q16[12])<<0 | uint32(q16[13])<<8 | uint32(q16[14])<<16 | uint32(q16[15])<<24)}
		t3 := vec128{uint32(t0.L0 + t2.L0), uint32(t0.L1 + t2.L1), uint32(t0.L2 + t2.L2), uint32(t0.L3 + t2.L3)}
		v1 = t3
		v2 = v2 + int32(16)
		v0 = v0 - int32(1)
		goto l1
	}
}
