// Code generated by wasm2go. DO NOT EDIT.

//go:build 386 || amd64 || arm64 || loong64 || ppc64le || wasm

package wasm2go

import (
	wasm2go_functions1 "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/functions1"
	wasm2go_functions2 "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/functions2"
	wasm2go_functions3 "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/functions3"
	wasm2go_functions4 "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/functions4"
	wasm2go_functions5 "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/functions5"
	wasm2go_functions6 "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/functions6"
	wasm2go_instance "github.com/stricttools/wasm-to-go/testdata/packages/bce/internal/instance"
)

type Module struct {
	instance wasm2go_instance.Module
}
type Memory = wasm2go_instance.Memory

func New() *Module {
	m := new(Module)
	s := &m.instance
	s.MaxMem = 65536
	s.Memory = make([]byte, 65536)
	return m
}
func (m *Module) Xmemory() Memory {
	return (*wasm2go_instance.WasmMemory)(&m.instance.Memory)
}
func (m *Module) Xbranch(v0, v1 int32) int32 {
	return wasm2go_functions2.Xbranch(&m.instance, v0, v1)
}
func (m *Module) Xcopy(v0 int32) int32 {
	return wasm2go_functions1.Xcopy(&m.instance, v0)
}
func (m *Module) Xinc(v0 int32) {
	wasm2go_functions5.Xinc(&m.instance, v0)
}
func (m *Module) Xsum(v0 int32) int32 {
	return wasm2go_functions6.Xsum(&m.instance, v0)
}
func (m *Module) Xwalk(v0, v1 int32) int32 {
	return wasm2go_functions3.Xwalk(&m.instance, v0, v1)
}
func (m *Module) Xwiden(v0 int32) int64 {
	return wasm2go_functions4.Xwiden(&m.instance, v0)
}
