// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions5

import "github.com/stricttools/wasm-to-go/testdata/packages/simd_api/internal/instance"

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Fn4(m *instance.Module, v0 vec128) {
	t0 := v0
	m.G1 = [16]byte{byte(t0.L0), byte((t0.L0 >> 8)), byte((t0.L0 >> 16)), byte((t0.L0 >> 24)), byte(t0.L1), byte((t0.L1 >> 8)), byte((t0.L1 >> 16)), byte((t0.L1 >> 24)), byte(t0.L2), byte((t0.L2 >> 8)), byte((t0.L2 >> 16)), byte((t0.L2 >> 24)), byte(t0.L3), byte((t0.L3 >> 8)), byte((t0.L3 >> 16)), byte((t0.L3 >> 24))}
	t1 := v0
	*m.G0 = [16]byte{byte(t1.L0), byte((t1.L0 >> 8)), byte((t1.L0 >> 16)), byte((t1.L0 >> 24)), byte(t1.L1), byte((t1.L1 >> 8)), byte((t1.L1 >> 16)), byte((t1.L1 >> 24)), byte(t1.L2), byte((t1.L2 >> 8)), byte((t1.L2 >> 16)), byte((t1.L2 >> 24)), byte(t1.L3), byte((t1.L3 >> 8)), byte((t1.L3 >> 16)), byte((t1.L3 >> 24))}
}
