// Code generated by wasm2go. DO NOT EDIT.

//go:build !(386 || amd64 || arm64 || loong64 || ppc64le || wasm)

package wasm2go

type Module struct {
	_env Xenv
}

func New(v0 Xenv) *Module {
	m := new(Module)
	m._env = v0
	if i, ok := any(v0).(interface {
		Init(any)
	}); ok {
		i.Init(m)
	}
	return m
}

type Xenv = interface {
	Xfn(v0 int32)
}

func (m *Module) fn0(v0 int32) {
	m._env.Xfn(v0)
}
func (m *Module) Xtee_self_loop(v0 int32) {
l0:
	m.fn0(v0)
	if v0 != 0 {
		goto l0
	}
}
