// Code generated by wasm2go. DO NOT EDIT.

package wasm2go

import (
	"math"
	"math/bits"
)

type Module struct {
	memory []byte
	maxMem int64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 65536
	m.memory = make([]byte, 65536)
	return m
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory []byte

func (m *wasmMemory) Slice() *[]byte {
	return (*[]byte)(m)
}
func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow((*[]byte)(m), delta, max)
}
func (m *Module) Xsin(v0 float64) float64 {
	var v1, v2 float64
	var v3 int32
	var v4 int64
	if v0 == math.Float64frombits(0x0) {
		return v0
	}
	v1 = math.Float64frombits(0x7ff8000000000000)
	{
		if uint64(int64(math.Float64bits(v0))&int64(0x7fffffffffffffff)) > uint64(int64(0x7fefffffffffffff)) {
			goto l0
		}
		t0 := v0
		v4 = i64_trunc_sat_f64_s(float64(float64(v0*math.Float64frombits(0x3fe45f306dc9c883)) + math.Copysign(math.Float64frombits(0x3fe0000000000000), v0)))
		v1 = f64_canon(float64(t0 + float64(float64(v4)*math.Float64frombits(0xbff921fb54442d18))))
		var p1 float64
	l1:
		{
			var p2 float64
			if f64_abs(v1) > math.Float64frombits(0x3e40000000000000) {
				v3 = v3 + int32(1)
				v1 = f64_canon(float64(v1 * math.Float64frombits(0x3fe0000000000000)))
				goto l1
			} else {
				v0 = math.Float64frombits(0x3ff0000000000000)
			l2:
				if v3 != 0 {
					v3 = v3 - int32(1)
					v2 = f64_canon(float64(v1 * v1))
					v0 = f64_canon(float64(v0 * v1))
					v1 = f64_canon(float64(v0 + v0))
					v0 = f64_canon(float64(math.Float64frombits(0x3ff0000000000000) - float64(v2+v2)))
					goto l2
				} else {
					switch int32(v4)&int32(3) - int32(1) {
					case 1:
						return f64_neg(v1)
					case 2:
						goto l5
					default:
						goto l0
					case 0:
					}
				}
				return v0
			l5:
				p2 = f64_neg(v0)
			}
			p1 = p2
		}
		v1 = p1
	}
l0:
	return v1
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(&m.memory)
}

//go:nosplit
func i32(x int32) int32 { return x }

//go:nosplit
func i64(x int64) int64 { return x }

//go:nosplit
func f64_abs(x float64) float64 {
	return math.Float64frombits(math.Float64bits(x) &^ (1 << 63))
}

//go:nosplit
func f64_neg(x float64) float64 {
	return math.Float64frombits(math.Float64bits(x) ^ 1<<63)
}

//go:nosplit
func f64_canon(x float64) float64 {
	if x != x {
		return math.Float64frombits(0x7ff8000000000000)
	}
	return x
}

//go:nosplit
func i64_trunc_sat_f64_s(f float64) int64 {
	switch {
	case f < math.MinInt64:
		return math.MinInt64
	case f >= math.MaxInt64:
		return math.MaxInt64
	case f != f:
		return 0
	}
	return int64(f)
}

func memory_grow(mem *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	*mem = append(buf, make([]byte, int(new<<16)-len)...)
	return int64(old)
}
