// Code generated by wasm2go. DO NOT EDIT.

//go:build 386 || amd64 || arm64 || loong64 || ppc64le || wasm

package wasm2go

import (
	"encoding/binary"
	"math"
	"math/bits"
	"runtime"
	"unsafe"
)

type Module struct {
	memory     []byte
	memBacking []byte
	maxMem     int64
}

func New() *Module {
	m := new(Module)
	m.maxMem = 2048
	m.memBacking = make([]byte, 65536)
	m.memory = m.memBacking
	return m
}

// MemoryMax is the most bytes the module's memory can grow to
// through its own memory.grow: its declared maximum.
func (m *Module) MemoryMax() int64 { return 134217728 }

// UseMemory moves the module's memory to the start of buf's backing array,
// where it keeps its size and contents and grows in place, without
// copying or allocating, as far as buf's capacity allows (past it, it moves
// to a new array in the Go heap). buf's bytes past the memory's size must
// be zero, and nothing else may write to them. UseMemory returns false,
// and leaves the memory where it is, when buf's capacity is less than the
// memory's size (a nil buf included). Slices of the memory taken before
// the call are stale after it, as after the memory grows.
func (m *Module) UseMemory(buf []byte) bool {
	n := len(m.memory)
	if cap(buf) < n {
		return false
	}
	buf = buf[:cap(buf)]
	copy(buf, m.memory)
	m.memBacking = buf
	m.memory = buf[:n:n]
	return true
}

type Memory = interface {
	Slice() *[]byte
	Grow(delta, max int64) int64
}
type wasmMemory Module

func (m *wasmMemory) Slice() *[]byte { return &m.memory }

func (m *wasmMemory) Grow(delta, max int64) int64 {
	return memory_grow(&m.memory, &m.memBacking, delta, max)
}
func (m *Module) Xgrow_to(v0 int32) int32 {
	mem := m.memory
	var v1 int32
l1:
	{
		t0 := int32(len(mem) >> 16)
		if uint32(t0) >= uint32(v0) {
			goto l0
		}
		t1 := int32(memory_grow(&m.memory, &m.memBacking, int64(int32(1)), m.maxMem))
		mem = m.memory
		v1 = t1
		if v1 == int32(-1) {
			goto l0
		}
		memory_fill(mem, uint32(v1<<16), int32(171), uint32(int32(65536)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(v1<<16))+3]), -3)) = uint32(v1)
		goto l1
	}
l0:
	t2 := int32(len(mem) >> 16)
	return t2
}
func (m *Module) Xgrow(v0 int32) int32 {
	t0 := int32(memory_grow(&m.memory, &m.memBacking, int64(v0), m.maxMem))
	return t0
}
func (m *Module) Xsum() int32 {
	mem := m.memory
	var v0, v1 int32
l1:
	{
		t0 := int32(len(mem) >> 16)
		if uint32(v0) >= uint32(t0) {
			return v1
		}
		t1 := int32(*(*uint32)(unsafe.Add(unsafe.Pointer(&mem[uint64(uint32(v0<<16))+3]), -3)))
		v1 = v1 + t1
		v0 = v0 + int32(1)
		goto l1
	}
}
func (m *Module) Xmemory() Memory {
	return (*wasmMemory)(m)
}

// Compiler error if endianess is unknown.
var _ = map[bool]struct{}{big: {}, little: {}}

// go.dev/src/cmd/compile/internal/ssa/config.go
const (
	big = false ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "s390x" ||
		runtime.GOARCH == "mips" || runtime.GOARCH == "mips64"

	little = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm" || runtime.GOARCH == "arm64" ||
		runtime.GOARCH == "riscv64" || runtime.GOARCH == "wasm" ||
		runtime.GOARCH == "ppc64le" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "mipsle" || runtime.GOARCH == "mips64le"

	unalignedOK = false ||
		runtime.GOARCH == "386" || runtime.GOARCH == "amd64" ||
		runtime.GOARCH == "arm64" || runtime.GOARCH == "loong64" ||
		runtime.GOARCH == "ppc64" || runtime.GOARCH == "ppc64le" ||
		runtime.GOARCH == "s390x" || runtime.GOARCH == "wasm"
)

//go:nosplit
func load32[T uint32 | uint64](mem []byte, addr T) uint32 {
	if !unalignedOK {
		return binary.LittleEndian.Uint32(mem[addr:])
	}
	_ = mem[uint64(addr)+3]
	val := *(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr)))
	if big {
		return bits.ReverseBytes32(val)
	}
	return val
}

//go:nosplit
func store32[T uint32 | uint64](mem []byte, addr T, val uint32) {
	if !unalignedOK {
		binary.LittleEndian.PutUint32(mem[addr:], val)
		return
	}
	if big {
		val = bits.ReverseBytes32(val)
	}
	_ = mem[uint64(addr)+3]
	*(*uint32)(unsafe.Add(unsafe.Pointer(unsafe.SliceData(mem)), uintptr(addr))) = val
}

//go:nosplit
func i32(x int32) int32 { return x }

// Grows the memory *mem by delta pages, up to max, and returns its old size
// in pages, or -1. *back is the memory's backing array: *mem is its prefix,
// with its capacity cut to its length, so no slice of the memory reaches
// past its end, and back's bytes past the memory's end are zero. Growth
// within back is in place: no copy, no allocation. Past it, the memory moves
// to a new backing array of twice the size, at least what the growth needs,
// at most max pages.
func memory_grow(mem, back *[]byte, delta, max int64) int64 {
	buf := *mem
	len := len(buf)
	old := len >> 16
	if delta == 0 {
		return int64(old)
	}
	max = int64(min(uint64(max), math.MaxInt>>16))
	new, c := bits.Add64(uint64(old), uint64(delta), 0)
	if c != 0 || new > uint64(max) {
		return -1
	}
	size := int(new << 16)
	if size > cap(*back) {
		n := int(min(uint64(cap(*back))>>15, uint64(max)) << 16)
		if n < size {
			n = size
		}
		b := make([]byte, n)
		copy(b, buf)
		*back = b
	}
	*mem = (*back)[:size:size]
	return int64(old)
}

func memory_fill[T uint32 | uint64](mem []byte, dest T, val int32, n T) {
	mem = mem[:len(mem):len(mem)]
	x := uint64(dest)
	y := x + uint64(n)
	buf := mem[x:y]
	if len(buf) > 0 {
		buf[0] = byte(val)
		for i := 1; i < len(buf); {
			chunk := min(i, 8192)
			i += copy(buf[i:], buf[:chunk])
		}
	}
}
