// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions46

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"math/bits"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Xop110(m *instance.Module, v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v0) ^ int32(-0x80000000)))
	t5 := vec128f32{t3.F0, t3.F1, (t4), t3.F3}
	t6 := math.Float32frombits(uint32(int32(v1) ^ int32(-0x80000000)))
	t7 := vec128f32{t5.F0, t5.F1, t5.F2, (t6)}
	t8 := vec128f32{math.Float32frombits(math.Float32bits(t7.F0) &^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F1) &^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F2) &^ (1 << 31)), math.Float32frombits(math.Float32bits(t7.F3) &^ (1 << 31))}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits(t9.F0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits(t12.F1))
	t14 := t11 | int64(uint32(t13))<<32
	t15 := v2
	t16 := int32(math.Float32bits(t15.F2))
	t17 := int64(uint32(t16))
	t18 := v2
	t19 := int32(math.Float32bits(t18.F3))
	return t14 + i64_rotl(t17|int64(uint32(t19))<<32, int64(17))
}

//go:nosplit
func i64_rotl(x, y int64) int64 {
	return int64(bits.RotateLeft64(uint64(x), int(y)))
}
