// Code generated by wasm2go. DO NOT EDIT.

package functions8

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func Fn1(v0 vec128) vec128 {
	t0 := v0
	t1 := vec128{uint32(t0.L0 + (lane_u32(0x1))), uint32(t0.L1 + (lane_u32(0x1))), uint32(t0.L2 + (lane_u32(0x1))), uint32(t0.L3 + (lane_u32(0x1)))}
	return t1
}

// Prevents constant folding, as i32 does.
//
//go:nosplit
func lane_u32(x uint32) uint32 { return x }
