// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions59

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Xop97(m *instance.Module, v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float32frombits(uint32(int32(v0)))
	t1 := vec128f32{(t0), (t0), (t0), (t0)}
	t2 := math.Float32frombits(uint32(int32(v1)))
	t3 := vec128f32{t1.F0, (t2), t1.F2, t1.F3}
	t4 := math.Float32frombits(uint32(int32(v1)))
	t5 := vec128f32{(t4), (t4), (t4), (t4)}
	t6 := math.Float32frombits(uint32(int32(v0)))
	t7 := vec128f32{t5.F0, (t6), t5.F2, t5.F3}
	t8 := vec128f32{lane_pminf32(t3.F0, t7.F0), lane_pminf32(t3.F1, t7.F1), lane_pminf32(t3.F2, t7.F2), lane_pminf32(t3.F3, t7.F3)}
	v2 = t8
	t9 := v2
	t10 := int32(math.Float32bits(t9.F0))
	t11 := int64(uint32(t10))
	t12 := v2
	t13 := int32(math.Float32bits(t12.F1))
	return t11 | int64(uint32(t13))<<32
}

// The same, of lanes held as floats: moves keep their bits.
//
//go:nosplit
func lane_pminf32(a, b float32) float32 {
	if b < a {
		return b
	}
	return a
}
