// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions23

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"math/bits"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Xop133(m *instance.Module, v0, v1 int64) int64 {
	var v2 vec128f32
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f32{float32(t3.D0), float32(t3.D1), 0, 0}
	v2 = t4
	t5 := v2
	t6 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t5.F0))))))
	t7 := int64(uint32(t6))
	t8 := v2
	t9 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t8.F1))))))
	t10 := t7 | int64(uint32(t9))<<32
	t11 := v2
	t12 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t11.F2))))))
	t13 := int64(uint32(t12))
	t14 := v2
	t15 := int32(math.Float32bits((math.Float32frombits(lane_canon32(math.Float32bits(t14.F3))))))
	return t10 + i64_rotl(t13|int64(uint32(t15))<<32, int64(17))
}

//go:nosplit
func i64_rotl(x, y int64) int64 {
	return int64(bits.RotateLeft64(uint64(x), int(y)))
}

// The bits of a float32 lane, with a NaN made the positive canonical NaN,
// without a branch: the mask is all ones exactly when the magnitude is
// above the infinity's.
//
//go:nosplit
func lane_canon32(b uint32) uint32 {
	return b ^ (b^0x7fc00000)&-((b&0x7fffffff+0x7fffff)>>31)
}
