// Code generated by wasm2go. DO NOT EDIT.

//go:build goexperiment.simd && amd64.v3 && go1.27 && !go1.28

package wasm2go

import "simd/archsimd"

type vec128 = archsimd.Uint32x4

func fn0(v0 vec128, v1 int32) vec128 {
	t0 := v0
	t1 := v1
	t2 := t0.ReshapeToUint8s().ReshapeToUint16s().ShiftAllRight(uint64(uint32((t1)) & 7)).ReshapeToUint8s().And(archsimd.BroadcastUint8x16(uint8(0xff) >> uint64(uint32((t1))&7))).Xor(archsimd.BroadcastUint8x16(uint8(0x80) >> uint64(uint32((t1))&7))).Sub(archsimd.BroadcastUint8x16(uint8(0x80) >> uint64(uint32((t1))&7))).ReshapeToUint32s()
	return t2
}
func fn1(v0 vec128, v1 int32) vec128 {
	t0 := v0
	t1 := v1
	t2 := t0.ReshapeToUint16s().BitsToInt16().ShiftAllRight(uint64(uint32((t1)) & 15)).ToBits().ReshapeToUint32s()
	return t2
}
func fn2(v0 vec128, v1 int32) vec128 {
	t0 := v0
	t1 := v1
	t2 := t0.BitsToInt32().ShiftAllRight(uint64(uint32((t1)) & 31)).ToBits()
	return t2
}
func fn3(v0 vec128, v1 int32) vec128 {
	t0 := v0
	t1 := v1
	t2 := t0.ReshapeToUint64s().ShiftAllRight(uint64(uint32((t1)) & 63)).Xor(archsimd.BroadcastUint64x2(uint64(1) << 63 >> uint64(uint32((t1))&63))).Sub(archsimd.BroadcastUint64x2(uint64(1) << 63 >> uint64(uint32((t1))&63))).ReshapeToUint32s()
	return t2
}
func (m *Module) Xi16x8(v0 [16]byte, v1 int32) [16]byte {
	r := fn1(archsimd.LoadUint8x16Array(&v0).ReshapeToUint32s(), v1)
	return [16]byte{byte(r.GetElem(0)), byte((r.GetElem(0) >> 8)), byte((r.GetElem(0) >> 16)), byte((r.GetElem(0) >> 24)), byte(r.GetElem(1)), byte((r.GetElem(1) >> 8)), byte((r.GetElem(1) >> 16)), byte((r.GetElem(1) >> 24)), byte(r.GetElem(2)), byte((r.GetElem(2) >> 8)), byte((r.GetElem(2) >> 16)), byte((r.GetElem(2) >> 24)), byte(r.GetElem(3)), byte((r.GetElem(3) >> 8)), byte((r.GetElem(3) >> 16)), byte((r.GetElem(3) >> 24))}
}
func (m *Module) Xi32x4(v0 [16]byte, v1 int32) [16]byte {
	r := fn2(archsimd.LoadUint8x16Array(&v0).ReshapeToUint32s(), v1)
	return [16]byte{byte(r.GetElem(0)), byte((r.GetElem(0) >> 8)), byte((r.GetElem(0) >> 16)), byte((r.GetElem(0) >> 24)), byte(r.GetElem(1)), byte((r.GetElem(1) >> 8)), byte((r.GetElem(1) >> 16)), byte((r.GetElem(1) >> 24)), byte(r.GetElem(2)), byte((r.GetElem(2) >> 8)), byte((r.GetElem(2) >> 16)), byte((r.GetElem(2) >> 24)), byte(r.GetElem(3)), byte((r.GetElem(3) >> 8)), byte((r.GetElem(3) >> 16)), byte((r.GetElem(3) >> 24))}
}
func (m *Module) Xi64x2(v0 [16]byte, v1 int32) [16]byte {
	r := fn3(archsimd.LoadUint8x16Array(&v0).ReshapeToUint32s(), v1)
	return [16]byte{byte(r.GetElem(0)), byte((r.GetElem(0) >> 8)), byte((r.GetElem(0) >> 16)), byte((r.GetElem(0) >> 24)), byte(r.GetElem(1)), byte((r.GetElem(1) >> 8)), byte((r.GetElem(1) >> 16)), byte((r.GetElem(1) >> 24)), byte(r.GetElem(2)), byte((r.GetElem(2) >> 8)), byte((r.GetElem(2) >> 16)), byte((r.GetElem(2) >> 24)), byte(r.GetElem(3)), byte((r.GetElem(3) >> 8)), byte((r.GetElem(3) >> 16)), byte((r.GetElem(3) >> 24))}
}
func (m *Module) Xi8x16(v0 [16]byte, v1 int32) [16]byte {
	r := fn0(archsimd.LoadUint8x16Array(&v0).ReshapeToUint32s(), v1)
	return [16]byte{byte(r.GetElem(0)), byte((r.GetElem(0) >> 8)), byte((r.GetElem(0) >> 16)), byte((r.GetElem(0) >> 24)), byte(r.GetElem(1)), byte((r.GetElem(1) >> 8)), byte((r.GetElem(1) >> 16)), byte((r.GetElem(1) >> 24)), byte(r.GetElem(2)), byte((r.GetElem(2) >> 8)), byte((r.GetElem(2) >> 16)), byte((r.GetElem(2) >> 24)), byte(r.GetElem(3)), byte((r.GetElem(3) >> 8)), byte((r.GetElem(3) >> 16)), byte((r.GetElem(3) >> 24))}
}
