// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions42

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"math/bits"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}

func Xop114(m *instance.Module, v0, v1 int64) int64 {
	var v2, _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128{uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32), uint32(math.Float64bits((t0))), uint32((math.Float64bits((t0))) >> 32)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128{uint32((uint64(t1.L0) | uint64(t1.L1)<<32)), uint32((uint64(t1.L0) | uint64(t1.L1)<<32) >> 32), uint32(math.Float64bits((t2))), uint32((math.Float64bits((t2))) >> 32)}
	t4 := math.Float64frombits(uint64(v1))
	t5 := vec128{uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32), uint32(math.Float64bits((t4))), uint32((math.Float64bits((t4))) >> 32)}
	t6 := math.Float64frombits(uint64(v0))
	t7 := vec128{uint32((uint64(t5.L0) | uint64(t5.L1)<<32)), uint32((uint64(t5.L0) | uint64(t5.L1)<<32) >> 32), uint32(math.Float64bits((t6))), uint32((math.Float64bits((t6))) >> 32)}
	t8 := vec128{uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) * math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L0) | uint64(t3.L1)<<32)) * math.Float64frombits((uint64(t7.L0) | uint64(t7.L1)<<32)))))) >> 32), uint32(uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) * math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))), uint32((uint64(math.Float64bits(float64(math.Float64frombits((uint64(t3.L2) | uint64(t3.L3)<<32)) * math.Float64frombits((uint64(t7.L2) | uint64(t7.L3)<<32)))))) >> 32)}
	v2 = t8
	t9 := v2
	t10 := int64((uint64((uint32(uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t9.L0) | uint64(t9.L1)<<32))))>>32)))<<32))
	t11 := v2
	t12 := int64((uint64((uint32(uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32)))))) | uint64((uint32((uint64(lane_canon64((uint64(t11.L2) | uint64(t11.L3)<<32))))>>32)))<<32))
	return t10 + i64_rotl(t12, int64(17))
}

//go:nosplit
func i64_rotl(x, y int64) int64 {
	return int64(bits.RotateLeft64(uint64(x), int(y)))
}

//go:nosplit
func lane_canon64(b uint64) uint64 {
	return b ^ (b^0x7ff8000000000000)&-((b&0x7fffffffffffffff+0xfffffffffffff)>>63)
}
