// Code generated by wasm2go. DO NOT EDIT.

//go:build !(goexperiment.simd && (amd64.v3 || arm64 || wasm))

package functions24

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
	"math/bits"
)

type vec128 = struct {
	L0, L1, L2, L3 uint32
}
type vec128f32 = struct {
	F0, F1, F2, F3 float32
}
type vec128f64 = struct {
	D0, D1 float64
}

func Xop132(m *instance.Module, v0, v1 int64) int64 {
	var v2 vec128f64
	var _, _ vec128
	t0 := math.Float64frombits(uint64(v0))
	t1 := vec128f64{(t0), (t0)}
	t2 := math.Float64frombits(uint64(v1))
	t3 := vec128f64{t1.D0, (t2)}
	t4 := vec128f64{math.Float64frombits(math.Float64bits(t3.D0) ^ (1 << 63)), math.Float64frombits(math.Float64bits(t3.D1) ^ (1 << 63))}
	v2 = t4
	t5 := v2
	t6 := int64((uint64(uint32(math.Float64bits(t5.D0))) | uint64(uint32((math.Float64bits(t5.D0))>>32))<<32))
	t7 := v2
	t8 := int64((uint64(uint32(math.Float64bits(t7.D1))) | uint64(uint32((math.Float64bits(t7.D1))>>32))<<32))
	return t6 + i64_rotl(t8, int64(17))
}

//go:nosplit
func i64_rotl(x, y int64) int64 {
	return int64(bits.RotateLeft64(uint64(x), int(y)))
}
