// Code generated by wasm2go. DO NOT EDIT.

package functions24

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop45(m *instance.Module, v0, v1 int64) int64 {
	return i64_trunc_sat_f64_u(math.Float64frombits(uint64(v0)))
}

//go:nosplit
func i64_trunc_sat_f64_u(f float64) int64 {
	var i uint64
	switch {
	case f <= 0 || f != f:
		i = 0
	case f >= math.MaxUint64:
		i = math.MaxUint64
	default:
		i = uint64(f)
	}
	return int64(i)
}
