// Code generated by wasm2go. DO NOT EDIT.

package functions9

import "github.com/stricttools/wasm-to-go/testdata/packages/stack_bound/internal/instance"

func Fn0(m *instance.Module, v0 int32) int32 {
	if m.StackUsed += 1006; m.StackUsed > 201326592 {
		panic("call stack exhausted")
	}
	t0 := Fn0(m, v0+int32(1))
	{
		m.StackUsed -= 1006
		return t0 + int32(1)
	}
}
