// Code generated by wasm2go. DO NOT EDIT.

package functions30

import (
	"github.com/stricttools/wasm-to-go/testdata/packages/determinism/internal/instance"
	"math"
)

func Xop39(m *instance.Module, v0, v1 int64) int64 {
	return int64(uint32(i32_trunc_sat_f32_u(math.Float32frombits(uint32(int32(v0))))))
}

//go:nosplit
func i32_trunc_sat_f32_u(f float32) int32 {
	var i uint32
	switch {
	case f <= 0 || f != f:
		i = 0
	case f >= math.MaxUint32:
		i = math.MaxUint32
	default:
		i = uint32(f)
	}
	return int32(i)
}
